package h264

// Frame zig-zag scan for 4x4 blocks (Fig 8-14, frame mode).
var zigzag4x4 = [16]int{
	0, 1, 4, 8, 5, 2, 3, 6, 9, 12, 13, 10, 7, 11, 14, 15,
}

// Frame zig-zag scan for 8x8 blocks: anti-diagonals in raster order,
// odd diagonals running up-right (generated by that rule, not copied).
var zigzag8x8 = [64]int{
	0, 1, 8, 16, 9, 2, 3, 10,
	17, 24, 32, 25, 18, 11, 4, 5,
	12, 19, 26, 33, 40, 48, 41, 34,
	27, 20, 13, 6, 7, 14, 21, 28,
	35, 42, 49, 56, 57, 50, 43, 36,
	29, 22, 15, 23, 30, 37, 44, 51,
	58, 59, 52, 45, 38, 31, 39, 46,
	53, 60, 61, 54, 47, 55, 62, 63,
}

// CAVLC 8x8 scan: four interleaved 16-coeff groups (spec 8x8 CAVLC
// order). Entry p holds the raster position of the p-th CAVLC scan
// slot; slices p=g*16..g*16+15 belong to sub-block g.
var zigzag8x8CAVLC = [64]int{
	0, 9, 17, 18, 12, 40, 27, 7,
	35, 57, 29, 30, 58, 38, 53, 47,
	1, 2, 24, 11, 19, 48, 20, 14,
	42, 50, 22, 37, 59, 31, 60, 55,
	8, 3, 32, 4, 26, 41, 13, 21,
	49, 43, 15, 44, 52, 39, 61, 62,
	16, 10, 25, 5, 33, 34, 6, 28,
	56, 36, 23, 51, 45, 46, 54, 63,
}

// dequant8Init holds the 8x8 normAdjust classes per qP%6 (six
// positions classes); dequant8Scan maps the raster-derived index to
// the class column.
var dequant8Init = [6][6]int32{
	{20, 18, 32, 19, 25, 24},
	{22, 19, 35, 21, 28, 26},
	{26, 23, 42, 24, 33, 31},
	{28, 25, 45, 26, 35, 33},
	{32, 28, 51, 30, 40, 38},
	{36, 32, 58, 34, 46, 43},
}

var dequant8Scan = [16]int32{0, 3, 4, 3, 3, 1, 5, 1, 4, 5, 2, 5, 3, 1, 5, 1}

func levelScale8(m, x, y int) int32 {
	r := y*8 + x
	t := ((r >> 1) & 12) | (r & 3)
	return dequant8Init[m][dequant8Scan[t]]
}

// dequantInit holds normAdjust row classes per qP%6 (Table 8-13 facts:
// class 0 at even-even, class 1 at mixed, class 2 at odd-odd positions).
var dequantInit = [6][3]int32{
	{10, 13, 16},
	{11, 14, 18},
	{13, 16, 20},
	{14, 18, 23},
	{16, 20, 25},
	{18, 23, 29},
}

// chromaQP maps QPY + offset (clipped 0..51) to QPC (Table 8-15, 8-bit).
var chromaQPTable = [52]int32{
	0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
	18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
	29, 30, 31, 32, 32, 33, 34, 34, 35, 35, 36, 36, 37, 37, 37,
	38, 38, 38, 39, 39, 39, 39,
}

// ChromaQP maps a luma QP plus index offset to the chroma QP.
func ChromaQP(qpY, offset int32) int32 {
	qpi := qpY + offset
	if qpi < 0 {
		qpi = 0
	}
	if qpi > 51 {
		qpi = 51
	}
	return chromaQPTable[qpi]
}

func levelScale(m, x, y int) int32 {
	switch {
	case x%2 == 0 && y%2 == 0:
		return dequantInit[m][0]
	case x%2 == 1 && y%2 == 1:
		return dequantInit[m][2]
	default:
		return dequantInit[m][1]
	}
}

func clipPixel(v int32) uint8 {
	if v < 0 {
		return 0
	}
	if v > 255 {
		return 255
	}
	return uint8(v)
}

// itrans4x4Core is the exact integer inverse transform (8.5.12) on
// de-quantized coefficients in raster order, yielding residual samples.
func itrans4x4Core(c [16]int32) [16]int32 {
	var e, f [16]int32
	for i := 0; i < 4; i++ {
		s0 := c[i] + c[8+i]
		s1 := c[i] - c[8+i]
		s2 := (c[4+i] >> 1) - c[12+i]
		s3 := c[4+i] + (c[12+i] >> 1)
		e[i] = s0 + s3
		e[4+i] = s1 + s2
		e[8+i] = s1 - s2
		e[12+i] = s0 - s3
	}
	for i := 0; i < 4; i++ {
		s0 := e[4*i] + e[4*i+2]
		s1 := e[4*i] - e[4*i+2]
		s2 := (e[4*i+1] >> 1) - e[4*i+3]
		s3 := e[4*i+1] + (e[4*i+3] >> 1)
		f[4*i] = s0 + s3
		f[4*i+1] = s1 + s2
		f[4*i+2] = s1 - s2
		f[4*i+3] = s0 - s3
	}
	var out [16]int32
	for i := range out {
		out[i] = (f[i] + 32) >> 6
	}
	return out
}

// ITransform4x4 inverts one 4x4 block. coeff holds quantized levels in
// zig-zag scan order; qp is the block QP. Returns residual in raster order.
//
// De-quant scales by LevelScale(qP%6) times the flat default weight 16
// (no scaling lists in this stage) times 2^(qP/6); the product lands on a
// multiple of 64 so the 1/64 normalization is exact (matches the
// reference dequant-then->>6 pipeline with no rounding residue).
func ITransform4x4(coeff [16]int32, qp uint32) [16]int32 {
	m := int(qp % 6)
	shift := int(qp / 6)
	var c [16]int32
	for scan, v := range coeff {
		if v == 0 {
			continue
		}
		pos := zigzag4x4[scan]
		c[pos] = int32(int64(v) * int64(levelScale(m, pos%4, pos/4)) << uint(shift))
	}
	return itrans4x4Core(c)
}

// ITransform4x4WithDC inverts one 4x4 block whose DC is already
// de-quantized (luma Intra16x16 or chroma DC+AC path). ac holds raw AC
// levels in zig-zag scan order (entry 0 ignored); dc is the scaled DC
// value for raster position (0,0). Only the AC levels are scaled here.
func ITransform4x4WithDC(ac [16]int32, dc int32, qp uint32) [16]int32 {
	m := int(qp % 6)
	shift := int(qp / 6)
	var c [16]int32
	c[0] = dc
	for scan := 1; scan < 16; scan++ {
		v := ac[scan]
		if v == 0 {
			continue
		}
		pos := zigzag4x4[scan]
		c[pos] = int32(int64(v) * int64(levelScale(m, pos%4, pos/4)) << uint(shift))
	}
	return itrans4x4Core(c)
}

// ITransformLumaDC inverts the 4x4 luma DC Hadamard block (8.5.10).
// dc holds 16 quantized DC levels in zig-zag scan order; the output is
// 16 de-quantized DC values in 4x4 block-index order.
func ITransformLumaDC(dc [16]int32, qp uint32) [16]int32 {
	m := int(qp % 6)
	var c [16]int32
	for scan, v := range dc {
		// DC scan is transposed vs the 4x4 residual zigzag (matches the
		// reference decoder's transposed scan tables): swap x/y so the
		// second coeff lands at block (0,1), not (1,0).
		r := zigzag4x4[scan]
		c[(r%4)*4+r/4] = v
	}
	var t [16]int32
	for i := 0; i < 4; i++ {
		a, b, cc, dd := c[4*i], c[4*i+1], c[4*i+2], c[4*i+3]
		z0, z1 := a+b, a-b
		z2, z3 := cc-dd, cc+dd
		t[4*i], t[4*i+1], t[4*i+2], t[4*i+3] = z0+z3, z0-z3, z1-z2, z1+z2
	}
	var f [16]int32
	for i := 0; i < 4; i++ {
		t0, t1, t2, t3 := t[i], t[4+i], t[8+i], t[12+i]
		z0, z1 := t0+t2, t0-t2
		z2, z3 := t1-t3, t1+t3
		f[4*i], f[4*i+1], f[4*i+2], f[4*i+3] = z0+z3, z1+z2, z1-z2, z0-z3
	}
	var out [16]int32
	ls := levelScale(m, 0, 0)
	if qp >= 12 {
		shift := int(qp/6) - 2
		for i := range out {
			out[i] = f[i] * ls << shift
		}
	} else {
		shift := 2 - int(qp/6)
		add := int32(1) << (shift - 1)
		for i := range out {
			out[i] = (f[i]*ls + add) >> shift
		}
	}
	return out
}

// ITransformChromaDC inverts one 2x2 chroma DC block (8.5.11).
func ITransformChromaDC(dc [4]int32, qp uint32) [4]int32 {
	a, b, c, d := dc[0], dc[1], dc[2], dc[3]
	e0 := a + b
	e1 := a - b
	e2 := c - d
	e3 := c + d
	f0 := e0 + e3
	f1 := e1 + e2
	f2 := e0 - e3
	f3 := e1 - e2
	m := int(qp % 6)
	ls := levelScale(m, 0, 0)
	var out [4]int32
	vals := [4]int32{f0, f1, f2, f3}
	if qp >= 6 {
		shift := int(qp/6) - 1
		for i, v := range vals {
			out[i] = v * ls << shift
		}
	} else {
		// Truncating shift matches the reference >>7 pipeline.
		for i, v := range vals {
			out[i] = (v * ls) >> 1
		}
	}
	return out
}

// Scaled dequant (F9): flat weight 16 collapses bit-exact to the
// unscaled paths above (the +32/+128 roundings vanish on multiples).

// ITransform4x4Scaled inverts one 4x4 block with explicit raster
// weights w (scaling list, 16 = flat).
func ITransform4x4Scaled(coeff [16]int32, qp uint32, w [16]uint8) [16]int32 {
	m := int(qp % 6)
	shift := int(qp/6) + 2
	var c [16]int32
	for scan, v := range coeff {
		if v == 0 {
			continue
		}
		pos := zigzag4x4[scan]
		ls := levelScale(m, pos%4, pos/4)
		q := int64(v) * int64(ls) * int64(w[pos]) << uint(shift)
		c[pos] = int32((q + 32) >> 6)
	}
	return itrans4x4Core(c)
}

// ITransform4x4WithDCScaled inverts one 4x4 block whose DC is already
// scaled; AC levels use the raster weights (entry 0 ignored).
func ITransform4x4WithDCScaled(ac [16]int32, dc int32, qp uint32, w [16]uint8) [16]int32 {
	m := int(qp % 6)
	shift := int(qp/6) + 2
	var c [16]int32
	c[0] = dc
	for scan := 1; scan < 16; scan++ {
		v := ac[scan]
		if v == 0 {
			continue
		}
		pos := zigzag4x4[scan]
		ls := levelScale(m, pos%4, pos/4)
		q := int64(v) * int64(ls) * int64(w[pos]) << uint(shift)
		c[pos] = int32((q + 32) >> 6)
	}
	return itrans4x4Core(c)
}

// ITransformLumaDCScaled inverts the 4x4 luma DC block with explicit
// DC weight w0 (list position 0).
func ITransformLumaDCScaled(dc [16]int32, qp uint32, w0 uint8) [16]int32 {
	m := int(qp % 6)
	var c [16]int32
	for scan, v := range dc {
		r := zigzag4x4[scan]
		c[(r%4)*4+r/4] = v
	}
	var t [16]int32
	for i := 0; i < 4; i++ {
		a, b, cc, dd := c[4*i], c[4*i+1], c[4*i+2], c[4*i+3]
		z0, z1 := a+b, a-b
		z2, z3 := cc-dd, cc+dd
		t[4*i], t[4*i+1], t[4*i+2], t[4*i+3] = z0+z3, z0-z3, z1-z2, z1+z2
	}
	var f [16]int32
	for i := 0; i < 4; i++ {
		t0, t1, t2, t3 := t[i], t[4+i], t[8+i], t[12+i]
		z0, z1 := t0+t2, t0-t2
		z2, z3 := t1-t3, t1+t3
		f[4*i], f[4*i+1], f[4*i+2], f[4*i+3] = z0+z3, z1+z2, z1-z2, z0-z3
	}
	var out [16]int32
	ls := levelScale(m, 0, 0)
	shift := int(qp/6) + 2
	for i := range out {
		q := int64(f[i]) * int64(ls) * int64(w0) << uint(shift)
		out[i] = int32((q + 128) >> 8)
	}
	return out
}

// ITransformChromaDCScaled inverts one 2x2 chroma DC block with
// explicit DC weight w0.
func ITransformChromaDCScaled(dc [4]int32, qp uint32, w0 uint8) [4]int32 {
	a, b, c, d := dc[0], dc[1], dc[2], dc[3]
	e0 := a + b
	e1 := a - b
	e2 := c - d
	e3 := c + d
	vals := [4]int32{e0 + e3, e1 + e2, e0 - e3, e1 - e2}
	m := int(qp % 6)
	ls := levelScale(m, 0, 0)
	shift := int(qp/6) + 2
	var out [4]int32
	for i, v := range vals {
		q := int64(v) * int64(ls) * int64(w0) << uint(shift)
		out[i] = int32(q >> 7)
	}
	return out
}

// idct8_1d runs one 8-point inverse transform (reference 8x8 equations).
func idct8_1d(w [8]int32) [8]int32 {
	a0 := uint32(w[0] + w[4])
	a2 := uint32(w[0] - w[4])
	a4 := uint32((w[2] >> 1) - w[6])
	a6 := uint32((w[6] >> 1) + w[2])
	b0 := a0 + a6
	b2 := a2 + a4
	b4 := a2 - a4
	b6 := a0 - a6
	a1 := -w[3] + w[5] - w[7] - (w[7] >> 1)
	a3 := w[1] + w[7] - w[3] - (w[3] >> 1)
	a5 := -w[1] + w[7] + w[5] + (w[5] >> 1)
	a7 := w[3] + w[5] + w[1] + (w[1] >> 1)
	b1 := (a7 >> 2) + a1
	b3 := a3 + (a5 >> 2)
	b5 := (a3 >> 2) - a5
	b7 := a7 - (a1 >> 2)
	var out [8]int32
	out[0] = int32(b0 + uint32(b7))
	out[7] = int32(b0 - uint32(b7))
	out[1] = int32(b2 + uint32(b5))
	out[6] = int32(b2 - uint32(b5))
	out[2] = int32(b4 + uint32(b3))
	out[5] = int32(b4 - uint32(b3))
	out[3] = int32(b6 + uint32(b1))
	out[4] = int32(b6 - uint32(b1))
	return out
}

func itrans8x8Core(c [64]int32) [64]int32 {
	// Reference 8x8 inverse path (transposed frequency layout in,
	// raster residual out): vertical pass keeps columns, horizontal
	// pass transposes rows into columns, matching the reference
	// decoder's two-loop order and rounding.
	var blk [64]int32
	copy(blk[:], c[:])
	blk[0] += 32
	for i := 0; i < 8; i++ {
		var col [8]int32
		for y := 0; y < 8; y++ {
			col[y] = blk[i+y*8]
		}
		out := idct8_1d(col)
		for y := 0; y < 8; y++ {
			blk[i+y*8] = out[y]
		}
	}
	var out [64]int32
	for i := 0; i < 8; i++ {
		var row [8]int32
		for x := 0; x < 8; x++ {
			row[x] = blk[x+i*8]
		}
		r := idct8_1d(row)
		out[i+0*8] = r[0] >> 6
		out[i+1*8] = r[1] >> 6
		out[i+2*8] = r[2] >> 6
		out[i+3*8] = r[3] >> 6
		out[i+4*8] = r[4] >> 6
		out[i+5*8] = r[5] >> 6
		out[i+6*8] = r[6] >> 6
		out[i+7*8] = r[7] >> 6
	}
	return out
}

// ITransform8x8Scaled inverts one 8x8 block: coeff holds quantized
// levels in zigzag scan order, w the raster scaling list. Frequency
// storage is transposed (raster position transpose) so the transpose
// in the horizontal pass lands residual in raster order.
func ITransform8x8Scaled(coeff [64]int32, qp uint32, w [64]uint8) [64]int32 {
	m := int(qp % 6)
	shift := int(qp / 6)
	var c [64]int32
	for scan, v := range coeff {
		if v == 0 {
			continue
		}
		pos := zigzag8x8[scan]
		tp := (pos >> 3) | ((pos & 7) << 3)
		ls := levelScale8(m, pos%8, pos/8)
		q := int64(v) * int64(ls) * int64(w[pos]) << uint(shift)
		c[tp] = int32((q + 32) >> 6)
	}
	return itrans8x8Core(c)
}
