package h264

// VR2 ffmpeg parity: every gen_vr2.sh clip must decode byte-exact to the
// ffmpeg YUV oracle sampled on the same machine.
// Baseline: ../testdata/vr2_ffmpeg.json (ffmpeg 4.4.2, §12.1 VR2 row).
// Peer: ffmpeg decoder YUV output
// (ffmpeg -i clip -f rawvideo -pix_fmt yuv420p) against
// Decoder.DecodeNALU + FinishPicture. Pass line is zero byte difference
// per frame, no tolerance.
// Compare modes: "file" clips (no B frames) compare in decode order;
// "display" clips (B reorder) sort by POC first, the .yuv itself is in
// display order. Small clips run both packings (F15 dual path); 480p
// and up run AVCC only here, their AnnexB half stays pinned by the
// per-stage gates in bframes_test.go. Missing mp4/.yuv skips readably:
// .yuv files are generated by gen_vr2.sh and stay out of git, and the
// 1080p pair is local-only (~15MB oracle).

import (
	"crypto/md5"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"sort"
	"testing"

	"github.com/energye/gpui/video/mp4"
)

type vr2Stream struct {
	Width       int    `json:"width"`
	Height      int    `json:"height"`
	CodecName   string `json:"codec_name"`
	Profile     string `json:"profile"`
	ProfileIDC  int    `json:"profile_idc"`
	Level       int    `json:"level"`
	NbFrames    int    `json:"nb_frames"`
	AvgFPS      string `json:"avg_frame_rate"`
}

type vr2Decode struct {
	Frames   int     `json:"frames"`
	Compare  string  `json:"compare"`
	POC      []int32 `json:"decode_poc"`
	DispW    int     `json:"display_width"`
	DispH    int     `json:"display_height"`
	YUVBytes int     `json:"yuv_bytes"`
	YUVMD5   string  `json:"yuv_md5"`
}

type vr2Clip struct {
	File      string    `json:"file"`
	YUVFile   string    `json:"yuv_file"`
	Tracked   bool      `json:"tracked_mp4"`
	MP4Bytes  int       `json:"mp4_bytes"`
	Stream    vr2Stream `json:"stream"`
	Decode    vr2Decode `json:"decode"`
}

type vr2Baseline struct {
	Clips []vr2Clip `json:"clips"`
}

func TestVR2FFmpegParity(t *testing.T) {
	basePath := filepath.Join("..", "testdata", "vr2_ffmpeg.json")
	buf, err := os.ReadFile(basePath)
	if err != nil {
		t.Skipf("vr2 baseline missing: %v", err)
	}
	var base vr2Baseline
	if err := json.Unmarshal(buf, &base); err != nil {
		t.Fatalf("vr2 baseline bad json: %v", err)
	}
	if len(base.Clips) == 0 {
		t.Fatal("vr2 baseline has no clips")
	}
	for _, clip := range base.Clips {
		clip := clip
		t.Run(clip.File, func(t *testing.T) {
			mp4Path := filepath.Join("..", "testdata", clip.File)
			yuvPath := filepath.Join("..", "testdata", clip.YUVFile)
			if _, err := os.Stat(mp4Path); err != nil {
				t.Skipf("clip %s absent (%v)", clip.File, err)
			}
			yuv, err := os.ReadFile(yuvPath)
			if err != nil {
				t.Skipf("oracle %s absent (run video/testdata/gen_vr2.sh): %v", clip.YUVFile, err)
			}
			if len(yuv) != clip.Decode.YUVBytes {
				t.Fatalf("%s: oracle bytes %d want %d (regen with gen_vr2.sh)", clip.File, len(yuv), clip.Decode.YUVBytes)
			}
			sum := md5.Sum(yuv)
			if got := hex.EncodeToString(sum[:]); got != clip.Decode.YUVMD5 {
				t.Fatalf("%s: oracle md5 %s want %s (regen with gen_vr2.sh)", clip.File, got, clip.Decode.YUVMD5)
			}
			movie, err := mp4.ParseFile(mp4Path)
			if err != nil {
				t.Fatalf("ParseFile %s: %v", clip.File, err)
			}
			if movie.Video == nil {
				t.Fatalf("%s: no video track", clip.File)
			}
			v := movie.Video
			if clip.Stream.CodecName != "h264" {
				t.Fatalf("%s: baseline codec_name %q want h264", clip.File, clip.Stream.CodecName)
			}
			if int(v.Width) != clip.Stream.Width || int(v.Height) != clip.Stream.Height {
				t.Fatalf("%s: track %dx%d want %dx%d", clip.File, v.Width, v.Height, clip.Stream.Width, clip.Stream.Height)
			}
			if v.SampleCount != clip.Stream.NbFrames {
				t.Fatalf("%s: samples %d want %d", clip.File, v.SampleCount, clip.Stream.NbFrames)
			}
			avcc, err := ParseAVCC(v.AVCConfig)
			if err != nil {
				t.Fatalf("%s: avcc: %v", clip.File, err)
			}
			if int(avcc.Profile) != clip.Stream.ProfileIDC {
				t.Fatalf("%s: profile_idc %d want %d", clip.File, avcc.Profile, clip.Stream.ProfileIDC)
			}
			if !vr1ProfileMatch(avcc.Profile, clip.Stream.Profile) {
				t.Fatalf("%s: profile %q (idc %d) want %q", clip.File, avcc.ProfileName, avcc.Profile, clip.Stream.Profile)
			}
			if int(avcc.Level) != clip.Stream.Level {
				t.Fatalf("%s: level %d want %d", clip.File, avcc.Level, clip.Stream.Level)
			}
			sps, err := ParseSPS(avcc.SPS[0])
			if err != nil {
				t.Fatalf("%s: sps: %v", clip.File, err)
			}
			if int(sps.Width) != clip.Decode.DispW || int(sps.Height) != clip.Decode.DispH {
				t.Fatalf("%s: sps size %dx%d want display %dx%d", clip.File, sps.Width, sps.Height, clip.Decode.DispW, clip.Decode.DispH)
			}
			packings := map[string]func([][]byte) ([]byte, func([]byte) ([][]byte, error)){
				"avcc": avccWrap,
			}
			if clip.Decode.DispW*clip.Decode.DispH <= 96*96 {
				packings["annexb"] = annexBWrap
			}
			for name, wrap := range packings {
				pics, _ := decodeClip(t, mp4Path, wrap)
				if len(pics) != clip.Decode.Frames {
					t.Fatalf("%s/%s: frames %d want %d", clip.File, name, len(pics), clip.Decode.Frames)
				}
				if len(clip.Decode.POC) == len(pics) {
					for i, p := range pics {
						if p.POC != clip.Decode.POC[i] {
							t.Fatalf("%s/%s: decode POC %v want %v", clip.File, name, pocList(pics), clip.Decode.POC)
						}
					}
				}
				ordered := pics
				if clip.Decode.Compare == "display" {
					ordered = append([]*Picture(nil), pics...)
					sort.Slice(ordered, func(i, j int) bool { return ordered[i].POC < ordered[j].POC })
				} else if clip.Decode.Compare != "file" {
					t.Fatalf("%s: unknown compare %q", clip.File, clip.Decode.Compare)
				}
				assertClipExact(t, ordered, yuvPath, clip.Decode.DispW, clip.Decode.DispH)
			}
		})
	}
}

func pocList(pics []*Picture) []int32 {
	out := make([]int32, 0, len(pics))
	for _, p := range pics {
		out = append(out, p.POC)
	}
	return out
}
