package kit

// CoverageStatus for Ant-facing kit capability.
type CoverageStatus string

const (
	// CovReady — kit API exists and is Headless-tested.
	CovReady CoverageStatus = "ready"
	// CovPartial — base available; advanced props deferred.
	CovPartial CoverageStatus = "partial"
	// CovPrimitive — build via primitive only (no kit wrapper yet).
	CovPrimitive CoverageStatus = "primitive"
	// CovLater — planned M4+ / post-M6.
	CovLater CoverageStatus = "later"
)

// CoverageEntry maps one Ant Design component to framework support.
type CoverageEntry struct {
	Ant    string
	Status CoverageStatus
	// Via is kit type or primitive composition hint.
	Via string
	// Milestone when first landed.
	Since string
	Notes string
}

// AntCoverage is the §5.7对照 table (living; update as kit grows).
// Counts are intentional snapshots for M6 DoD.
func AntCoverage() []CoverageEntry {
	return []CoverageEntry{
		// General
		{Ant: "Button", Status: CovReady, Via: "kit.Button", Since: "M1", Notes: "P0 对齐 docs/antd/button.md §6（type/size/shape/variant/color/danger/ghost/block/loading/iconPlacement/a11y）；P1: preset 全色板、loading.delay、autoInsertSpace、wave、href/htmlType"},
		{Ant: "FloatButton", Status: CovReady, Via: "kit.FloatButton / FloatButtonGroup", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/float-button.md §6（type default|primary、shape circle|square、icon/content、tooltip、disabled、loading Ticker、onClick、Group trigger click|hover、open/onOpenChange 受控、placement 四向、closeIcon、a11y AriaLabel、Token 40×40 / square r=8）；P1: badge、BackTop、draggable、href/target/htmlType、semantic classNames/styles、ConfigProvider 全局、展开入场动画像素级、官网逐像素"},
		{Ant: "Icon", Status: CovReady, Via: "kit.Icon / primitive.Icon", Since: "M1", Notes: "P0 对齐 docs/antd/icon.md §6（name 注册表、size 默认16、color Token、rotate、spin Ticker+ReduceMotion、twoTone 实例/全局、SetPainter、CreateFromIconfont+RegisterSource 离线多源、装饰默认 a11y/AriaLabel、hit==layout==paint）；P1: 远程 iconfont.cn scriptUrl、extraCommonProps/真 DOM classNames、全量 SVG Path/上千官方字形、spin 动画像素级/官网哈希、ConfigProvider 全局 Icon 默认"},
		{Ant: "Typography", Status: CovReady, Via: "kit.Typography / NewText / NewTitle / NewParagraph / NewLink", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/typography.md §6（Text/Title/Paragraph/Link、level 1..5 字号 38/30/24/20/16、type secondary|success|warning|danger、disabled、copyable+onCopy+icon、editable Enter/Esc+onChange/onStart/onEnd/onCancel、ellipsis rows/expandable/collapsible/受控 expanded/middle/suffix、actions.placement、strong/code/mark/delete/underline/italic/keyboard、onClick、a11y Label、正文 14 Token、复制成功 Ticker）；P1: semantic classNames/styles、copyable.format/tooltips/tabIndex 深度、editable.autoSize/maxLength/enterIcon/triggerType 全矩阵、ellipsis.tooltip 像素级、复制成功动画像素级、ConfigProvider 全局、后缀/表格示例、官网逐像素"},
		// Layout
		{Ant: "Divider", Status: CovReady, Via: "kit.Divider", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/divider.md §6（orientation/vertical、size small|medium|large|unset margin 8/16/24、variant solid|dashed|dotted + dashed 糖、Title/plain/titlePlacement start|end|center、orientationMargin 默认 0.05、role=separator、Token colorSplit + lineWidth、hit==layout==paint）；P1: semantic classNames/styles 深度、orientationMargin 绝对 px / styles.content.margin 全矩阵、垂直 -0.06em 光学、dashed/dotted 官网纹样逐像素、ConfigProvider 全局"},
		{Ant: "Flex", Status: CovReady, Via: "kit.Flex", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/flex.md §6（orientation/vertical、gap small|medium|large|px 8/16/24、justify、align 默认水平 start/垂直 stretch、wrap、官方 basic/align/gap/wrap/combination、Token、AriaLabel、hit==layout==paint）；P1: flex CSS 简写、component、wrap-reverse、semantic classNames/styles、ConfigProvider 全局 flex 默认、官网逐像素"},
		{Ant: "Grid", Status: CovReady, Via: "kit.Row / kit.Col / NewGrid", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/grid.md §6（Row align/justify/wrap/gutter[h|hv]、Col span/offset/order/push/pull/flex、断点 span xs…xxxl + SetViewportWidth、官方 basic/gutter/offset/sort/flex/flex-align/flex-order/flex-stretch、gridColumns=24、AriaLabel、hit==layout==paint）；P1: gutter/align/justify 响应式 object 与 CSS 字符串 gutter、Col 响应式 object 全字段、useBreakpoint/playground、官方响应式三示例、semantic classNames/styles、ConfigProvider 全局、官网逐像素"},
		{Ant: "Layout", Status: CovReady, Via: "kit.Layout / Header / Sider / Content / Footer", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/layout.md §6（嵌套 Header/Sider/Content/Footer、hasSider 自动/强制、Header 高64、Sider width200/collapsed80/collapsible/collapsed/defaultCollapsed/theme dark|light/trigger 默认|自定义|隐藏/breakpoint+ViewportWidth/onCollapse/onBreakpoint/reverseArrow/overlay collapsedWidth=0、官方 basic/top/top-side/top-side-2/side/custom-trigger/collapsible-overlay/responsive、Token bodyBg/headerBg/siderBg、AriaLabel、hit==layout==paint）；P1: 固定头/固定侧栏、折叠宽度过渡动画像素级、semantic classNames/styles、ConfigProvider 全局、官网逐像素"},
		{Ant: "Space", Status: CovReady, Via: "kit.Space / SpaceCompact / SpaceAddon", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/space.md §6（size small|middle|large|px|[col,row] 默认 small=8、orientation/vertical、align auto→水平center、wrap 仅水平、separator 工厂、官方 base/vertical/size/align/wrap/separator/compact/compact-buttons、Space.Compact block+叠边 gap≈-lineWidth+Button 中间圆角清零、Space.Addon、Token 8/16/24、AriaLabel、hit==layout==paint）；P1: semantic classNames/styles、垂直方向紧凑布局、ConfigProvider 全局、size 双 gap 真 rowGap、逐角 radius、Addon 全语义、官网逐像素"},
		{Ant: "Splitter", Status: CovReady, Via: "kit.Splitter / SplitterPanel", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/splitter.md §6（orientation/vertical、Panel size/defaultSize/min/max px|%、resizable、collapsible+showCollapsibleIcon、lazy 预览、onResize/Start/End/onCollapse、多面板/嵌套 group、键盘条微调、Token splitBarSize=2/trigger=6/spinner=20、AriaLabel、hit==layout==paint）；P1: semantic classNames/styles、collapsible.motion 动画像素级、draggerIcon/自定义折叠图标、onDraggerDoubleClick 双击重置、destroyOnHidden 深度、ConfigProvider 全局、官网逐像素"},
		// Navigation
		{Ant: "Anchor", Status: CovReady, Via: "kit.Anchor", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/anchor.md §6（items/title/href/children、direction vertical|horizontal、affix 默认 true、showInkInFixed、bounds=5、offsetTop/targetOffset、getCurrentAnchor、onChange/onClick、replace History 映射、ink 指示条、ScrollTarget+SectionOffsets+SyncFromScroll 桌面滚动宿主、嵌套二级、a11y navigation+focus ring、Token linkPadding 4/16 inkW=2 fontSize=14）；P1: per-link targetOffset、semantic classNames/styles、ink 滑动动画、真 window history、ConfigProvider 全局、debug/官网逐像素"},
		{Ant: "Breadcrumb", Status: CovReady, Via: "kit.Breadcrumb", Since: "Base-ALL"},
		{Ant: "Dropdown", Status: CovReady, Via: "kit.Dropdown", Since: "M4", Notes: "P0 对齐 docs/antd/dropdown.md §6（trigger hover|click|contextMenu、placement 12 向、arrow/pointAtCenter、open/onOpenChange 受控、disabled、menu items danger/extra/icon/divider/一级 Children、外点/Esc、Token 面板 radiusLG=8 item pad 12×5、a11y menu/menuitem、hit==layout==paint、官方 basic/extra/placement/arrow/item/arrow-center/trigger/event）；P1: Dropdown.Button、popupRender/扩展菜单、多级菜单 gallery、菜单隐藏方式 overlay-open、右键完整 demo、loading、selectable、划词、semantic classNames/styles、destroyOnHidden 深度、ConfigProvider 全局、动画像素级、官网逐像素"},
		{Ant: "Menu", Status: CovReady, Via: "kit.Menu", Since: "M3", Notes: "P0 对齐 docs/antd/menu.md §6（mode vertical|horizontal|inline、items/children/group/divider、selectedKeys/defaultSelectedKeys 受控非受控、openKeys/defaultOpenKeys+onOpenChange、onClick/onSelect/onDeselect、multiple、selectable、disabled/danger/icon/title、theme light|dark + SubMenu ColorTheme、inlineCollapsed 宽80、inlineIndent=24、itemHeight=controlHeightLG=40、collapsed tooltip、键盘 Enter/方向、a11y menu/menuitem、Token 色板、hit==layout==paint、官方 horizontal/inline/inline-collapsed/tooltip/sider-current/vertical/theme/submenu-theme）；P1: semantic classNames/styles、动画像素级、overflowedIndicator 水平省略、forceSubMenuRender、popupRender、triggerSubMenuAction 延时、ConfigProvider 全局、switch-mode/style-class/custom-popup 示例、多级 popup 浮层深度、官网逐像素"},
		{Ant: "Pagination", Status: CovReady, Via: "kit.Pagination", Since: "M4", Notes: "P0 对齐 docs/antd/pagination.md §6（total 条目数/current/pageSize 受控非受控、onChange(page,pageSize)、disabled、size 24/32/40、align、simple+readOnly、showQuickJumper Enter 跳页、showSizeChanger+onShowSizeChange、showTotal、hideOnSinglePage、showLessItems、pageSizeOptions、totalBoundary 自动 sizeChanger、ellipsis jump±5、a11y navigation+focus ring、Token itemH、hit==layout==paint、官方 basic/align/more/changer/jump/mini/simple/controlled）；P1: itemRender 自定义、semantic classNames/styles、responsive 断点、showTitle tooltip、SelectProps 深度 sizeChanger、goButton、总数/全部展示/itemRender/style-class gallery、动画像素级、ConfigProvider 全局、官网逐像素"},
		{Ant: "Steps", Status: CovReady, Via: "kit.Steps", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/steps.md §6（items/title/content/subTitle/icon/disabled/单步 status、current/initial/status、onChange、orientation、size medium|small、type default|panel、variant filled|outlined、titlePlacement、percent 进度环、maxCount 折叠省略、a11y navigation+focus ring、Token icon 32/24、hit==layout==paint、loading icon Ticker、官方 simple/error/vertical/clickable/panel/icon/title-placement/max-count）；P1: type=dot|navigation|inline、responsive 断点、iconRender/progressDot 钩子、semantic classNames/styles、动画像素级、ConfigProvider 全局、progress-dot/nav/inline gallery、官网逐像素"},
		{Ant: "Tabs", Status: CovReady, Via: "kit.Tabs", Since: "M3", Notes: "P0 对齐 docs/antd/tabs.md §6（items/TabItem label+children+icon+disabled、activeKey/defaultActiveKey 受控非受控、onChange/onTabClick、type line|card|editable-card+onEdit remove/add+hideAdd、size small|middle|large、centered、indicator size/align、tabBarExtraContent、tabPlacement top|bottom|left|right、destroyOnHidden、键盘方向、line ink+Ticker 滑动、Token gutter32/cardHeight40、a11y tablist/tab+focus ring、hit==layout==paint、官方 basic/disabled/centered/icon/indicator/slide/extra/size）；P1: more 折叠菜单、renderTabBar/可拖拽、semantic classNames/styles、ink/tabPane 动画像素级、placement/card/editable 完整 gallery 页、自定义新增触发器、ConfigProvider 全局、官网逐像素"},
		// Data Entry
		{Ant: "AutoComplete", Status: CovReady, Via: "kit.AutoComplete", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/auto-complete.md §6（value/defaultValue/onChange 受控、onSearch/onSelect、disabled、size 24/32/40、variant outlined|filled|borderless|underlined、status error|warning、open/defaultOpen/onOpenChange、options+一层 group、filterOption bool|func、defaultActiveFirstOption、allowClear/onClear、notFoundContent、children Input|Search|TextArea、popupMatchSelectWidth、loading Ticker、键盘 ↑↓EnterEsc、a11y combobox/listbox、官方 basic/options/custom/non-case-sensitive/certain-category/uncertain-category/status/variant）；P1: backfill、virtual 虚拟滚动、popupRender、semantic classNames/styles、自定义清除按钮/style-class 示例、动画像素级、ConfigProvider 全局、官网逐像素"},
		{Ant: "Cascader", Status: CovReady, Via: "kit.Cascader", Since: "M4", Notes: "P0 对齐 docs/antd/cascader.md §6（value/defaultValue/onChange 单选路径、multiple+onChangeMulti、options CascaderOption、disabled、size 24/32/40、variant outlined|filled|borderless|underlined、status error|warning、open/defaultOpen/onOpenChange、placement 四角、allowClear 默认 true、placeholder、changeOnSelect、expandTrigger click|hover、displayRender、showCheckedStrategy SHOW_PARENT|SHOW_CHILD、showSearch 路径过滤、loadData+Loading Ticker、自定义 TriggerNode、a11y combobox/listbox+focus ring、官方 basic/default-value/custom-trigger/hover/disabled-option/change-on-select/multiple/showCheckedStrategy）；P1: showSearch 对象形态 filter/limit/sort/render、tagRender/optionRender/popupRender/fieldNames、maxTagCount=responsive 像素级、虚拟长列、semantic classNames/styles、动画像素级、ConfigProvider 全局、大小/自定义已选项/搜索高级/动态加载完整 demo 视觉、官网逐像素"},
		{Ant: "Checkbox", Status: CovReady, Via: "kit.Checkbox / CheckboxGroup", Since: "M2", Notes: "P0 对齐 docs/antd/checkbox.md §6（checked/defaultChecked/controlled、indeterminate、onChange、disabled、title、Group value/defaultValue/options/name、Add+SetBody 布局、a11y role=checkbox、Token 指示器16×16 r=4、官方 basic/disabled/controller/group/check-all/layout/style-class/_semantic）；P1: semantic classNames/styles 函数形态深度、onFocus/onBlur、Wave/动画像素级、ConfigProvider 全局、debug/官网逐像素"},
		{Ant: "ColorPicker", Status: CovReady, Via: "kit.ColorPicker", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/color-picker.md §6（value/defaultValue/onChange/onChangeComplete、open/onOpenChange、size 24/32/40、mode single|gradient、showText+自定义文本钩子、disabled、disabledAlpha、allowClear/onClear、format hex|rgb|hsb、placement 四角、trigger click|hover、TriggerNode、HSB 面板+滑条、Token 色块/面板宽234、a11y combobox+focus ring、hit==layout==paint、官方 base/size/controlled/line-gradient/text-render/disabled/disabled-alpha/allowClear）；P1: presets 预设色、面板 format 切换 UI/disabledFormat/onFormatChange、panelRender、arrow 像素级、自定义触发器完整 demo/自定义 trigger 事件 demo、semantic classNames/styles、多 stop 渐变编辑器深度、动画像素级、ConfigProvider 全局、debug/官网逐像素"},
		{Ant: "DatePicker", Status: CovReady, Via: "kit.DatePicker / NewRangePicker", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/date-picker.md §6（value/defaultValue/onChange、picker date|week|month|quarter|year、format+FormatMask、showTime、needConfirm、multiple、RangePicker、disabled/disabledDate、size 24/32/40、variant、status、open/onOpenChange、placement 四角、allowClear、官方 basic/range/multiple/needConfirm/switchable/format/time/mask、a11y combobox+focus ring、hit==layout==paint）；P1: 受控 mode 面板、minDate/maxDate/presets/cellRender、输入 mask 逐键编辑深度、semantic classNames/styles、动画像素级、ConfigProvider 全局、禁用/允许留空/日期限定完整 demo、官网逐像素"},
		{Ant: "Form", Status: CovReady, Via: "kit.Form / FormItem / FormList", Since: "M3", Notes: "P0 对齐 docs/antd/form.md §6（layout horizontal|vertical|inline、disabled、size 24/32/40、variant outlined|filled|borderless|underlined、colon/labelAlign/labelCol/wrapperCol、requiredMark default|optional|hidden、initialValues+resetFields、rules/required/validator、validateTrigger onChange|onBlur、dependencies、valuePropName value|checked、onFinish/onFinishFailed/onValuesChange、实例 set/get/validate/submit、Form.List add/remove、嵌套 name、官方 basic/control-hooks/layout/layout-multiple/disabled/variant/required-mark/size、Token itemGap24、a11y label/error）；P1: scrollToFirstError、hasFeedback+validating Ticker、fields 受控、feedbackIcons、validateMessages、shouldUpdate/noStyle/getValueProps+normalize、preserve 精细、Form.Provider、其余示例、semantic classNames/styles、ConfigProvider 全局、官网逐像素"},
		{Ant: "Input", Status: CovReady, Via: "kit.Input / Search / Password / TextArea", Since: "M2", Notes: "P0 对齐 docs/antd/input.md §6（value/defaultValue/onChange 受控、disabled/readOnly、maxLength、onPressEnter、size 24/32/40、type text|password、variant outlined|filled|borderless|underlined、status error|warning、allowClear、prefix/suffix、Input.Search onSearch+enterButton+loading Ticker、Input.TextArea rows+autoSize min/maxRows、Input.Password visibilityToggle 掩码、a11y textbox+AriaLabel、Token paddingInline≈11/radius6、hit==layout==paint）；P1: showCount/count CountConfig、Input.OTP、formatter 展示、searchIcon/iconRender 深度、semantic classNames/styles、ConfigProvider 全局、debug/官网逐像素"},
		{Ant: "InputNumber", Status: CovReady, Via: "kit.InputNumber", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/input-number.md §6（value/defaultValue/onChange 受控、min/max/step/precision、controls/keyboard/changeOnWheel/changeOnBlur、disabled/readOnly、size 24/32/40、variant outlined|filled|borderless|underlined、status error|warning、mode input|spinner API、stringMode、formatter/parser、onStep/onPressEnter、a11y spinbutton、Token controlWidth90/handleWidth、官方 basic/size/disabled/digit/formatter/keyboard/change-on-wheel/variant）；P1: 前缀/后缀、超出边界完整 demo、自定义 up/down 图标、拨轮完整视觉、semantic classNames/styles、动画像素级、ConfigProvider 全局、debug/官网逐像素"},
		{Ant: "Mentions", Status: CovReady, Via: "kit.Mentions", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/mentions.md §6（value/defaultValue/onChange、disabled/readOnly、size 字号档、variant outlined|filled|borderless|underlined、status error|warning、options、prefix 默认@/多触发、split、placement top|bottom、allowClear/onClear、onSearch/onSelect、filterOption、loading Ticker、rows 多行、GetMentions、a11y combobox/listbox+键盘、官方 basic/size/variant/async/form/prefix/readonly/placement）；P1: allowClear 自定义 clearIcon 完整 demo、autoSize、自定义 status 完整页、validateSearch/onPopupScroll、semantic classNames/styles、动画像素级、ConfigProvider 全局、官网逐像素"},
		{Ant: "Radio", Status: CovReady, Via: "kit.Radio / RadioGroup / Radio.Button", Since: "M2", Notes: "P0 对齐 docs/antd/radio.md §6（checked/defaultChecked/controlled、Group value/defaultValue/options/name、onChange、disabled、size 24/32/40 仅 button、optionType default|button、buttonStyle outline|solid、block、orientation/vertical、title、Radio.Button、a11y role=radio/radiogroup+focus ring+方向键、Token 圆点16/Button高32、hit==layout==paint、官方 basic/disabled/radiogroup/radiogroup-more/radiogroup-block/radiogroup-options/radiobutton/radiogroup-with-name）；P1: semantic classNames/styles 函数形态、size.tsx/radiobutton-solid 完整页、_semantic、Wave/动画像素级、ConfigProvider 全局、debug/官网逐像素"},
		{Ant: "Rate", Status: CovReady, Via: "kit.Rate", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/rate.md §6（value/defaultValue/controlled float64、onChange/onHoverChange、disabled、size small|middle|large→starSize 15/20/25、count、allowClear 默认 true、allowHalf 半星命中+clip 绘制、character 字符串/CharacterAt(index)、tooltips string[]、keyboard 方向键、a11y radiogroup/radio+focus ring、Token yellow6 填充/fillSecondary 空底、hit==layout==paint、Root 身份稳定、官方 basic/size/half/text/disabled/clear/character/character-function）；P1: character 复杂节点/图标、tooltips 完整 TooltipProps、hover scale(1.1) 像素级、semantic classNames/styles、ConfigProvider 全局、动画像素级、debug/官网逐像素"},
		{Ant: "Select", Status: CovReady, Via: "kit.Select", Since: "M3", Notes: "P0 对齐 docs/antd/select.md §6（value/defaultValue/onChange 单选、Values/onChangeMulti 多选 tags、disabled、loading Ticker 后缀、size 24/32/40、variant outlined|filled|borderless|underlined、status error|warning、open/defaultOpen/onOpenChange 受控、options、title、placement 四角、allowClear/onClear、showSearch+optionFilterProp/filterOption/filterSort/onSearch、mode single|multiple|tags、maxTagCount +N 折叠、optionRender、notFoundContent、defaultActiveFirstOption、popupMatchSelectWidth、listHeight=256、键盘 ↑↓EnterEsc、a11y combobox/listbox+focus ring、Token 高度/圆角/边框、hit==layout==paint、官方 basic/search/search-filter-option/search-multi-field/multiple/size/option-render/search-sort）；P1: semantic classNames/styles、动画像素级/虚拟列表、optgroup 分组、联动 coordinate、label-in-value 完整、自动分词、前后缀、popupRender 扩展菜单、隐藏已选、variant/status 完整 gallery、maxCount、响应式 maxTagCount、大数据、ConfigProvider 全局、官网逐像素"},
		{Ant: "Slider", Status: CovReady, Via: "kit.Slider", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/slider.md §6（value/defaultValue/controlled、min/max/step/stepNull、onChange/onChangeComplete、range+Values/OnRangeChange、disabled、keyboard、marks/included/dots、orientation/vertical、tooltip open Auto|Always|Never + formatter/formatterNull + placement、a11y role=slider、Token controlSize10/railSize4/handleSize10/handleHover12/dotSize8、官方 basic/input-number/icon-slider/tip-formatter/event/mark/vertical/show-tooltip）；P1: reverse、range.draggableTrack、multiple/editable/maxCount、range 单柄 disabled[]、semantic classNames/styles、handle hover 动画像素级、ConfigProvider 全局、debug/官网逐像素"},
		{Ant: "Switch", Status: CovReady, Via: "kit.Switch", Since: "M2", Notes: "P0 对齐 docs/antd/switch.md §6（checked/value、defaultChecked/defaultValue、controlled、onChange/onClick、disabled、loading、size medium|small、checkedChildren/unCheckedChildren 字符串、a11y role=switch Space/Enter+focus ring、Token 轨 44×22/28×16 + colorPrimary 开态/colorTextQuaternary 关态、thumb FloatAnim+loading Ticker、hit==layout==paint）；P1: semantic classNames/styles、复杂 ReactNode 内文、Wave/像素级 handle 拉伸、官网逐像素"},
		{Ant: "TimePicker", Status: CovReady, Via: "kit.TimePicker / NewTimeRangePicker", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/time-picker.md §6（value/defaultValue/onChange TimeValue、disabled、size 24/32/40、variant outlined|filled|borderless|underlined、status error|warning、open/defaultOpen/onOpenChange、placement 四角、allowClear/onClear、format 列显隐、hour/minute/secondStep、needConfirm+OK、showNow、disabledTime、use12Hours L1、Range/NewTimeRangePicker L1、renderExtraFooter、loading Ticker、a11y combobox+focus ring、Token 高度/圆角、hit==layout==paint、官方 basic/value/size/need-confirm/disabled/hide-column/interval-options/addon）；P1: cellRender/hideDisabledOptions/changeOnScroll 像素级、semantic classNames/styles、12h/range/variant/status/suffix 完整 gallery 页、列虚拟滚动、ConfigProvider 全局、官网逐像素"},
		{Ant: "Transfer", Status: CovReady, Via: "kit.Transfer", Since: "M4", Notes: "P0 对齐 docs/antd/transfer.md §6（dataSource/targetKeys 受控、selectedKeys/onSelectChange、onChange(direction,moveKeys)、disabled、status error|warning、oneWay+右栏移除、showSearch+filterOption+onSearch、showSelectAll、actions/titles、render 字符串、footer、pagination pageSize=10 simple、ListBody 表格穿梭、操作钮 loading Ticker、Token listWidth180/listHeight200/listWidthLG250/header40/item32、a11y group/listbox、官方 basic/oneWay/search/advanced/custom-item/actions/large-data/table-transfer）；P1: semantic classNames/styles、selectionsIcon 顶栏下拉、selectAllLabels、树穿梭 tree-transfer、style-class/_semantic、动画像素级/超大虚拟、ConfigProvider 全局、官网逐像素"},
		{Ant: "TreeSelect", Status: CovReady, Via: "kit.TreeSelect", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/tree-select.md §6（value/defaultValue/onChange 单选、Values/onChangeMulti 多选、treeData TreeSelectNode、disabled、size 24/32/40、variant outlined|filled|borderless|underlined、status error|warning、open/defaultOpen/onOpenChange、placement 四角、allowClear/onClear、showSearch+onSearch、multiple、treeCheckable+showCheckedStrategy SHOW_CHILD|PARENT|ALL、treeCheckStrictly、treeDefaultExpandAll、treeLine/treeIcon、treeDataSimpleMode、loadData+Loading Ticker、title、listHeight=256、popupMatchSelectWidth、键盘 ↑↓←→EnterEsc、a11y combobox/option+focus ring、Token 高度/圆角/边框、hit==layout==paint、官方 basic/multiple/treeData/checkable/async/treeLine/placement/variant）；P1: semantic classNames/styles、动画像素级/复杂虚拟列表、maxCount、前后缀 suffix/prefix、自定义状态完整页、自定义语义 class、labelInValue 完整、fieldNames、switcherIcon 自定义、浏览器-only API、ConfigProvider 全局、官网逐像素"},
		{Ant: "Upload", Status: CovReady, Via: "kit.Upload / NewUploadDragger", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/upload.md §6（fileList/defaultFileList/Controlled、onChange、UploadFile.status/percent、disabled、listType text|picture|picture-card|picture-circle、type select|drag、customRequest 桌面主路径+默认 Ticker 模拟、beforeUpload Proceed|SkipUpload|Reject、onRemove/onPreview/onDrop、maxCount 1 替换/>1 截断、accept 扩展名/MIME、multiple、showUploadList、pastable+PasteFiles/PasteProvider、DropFiles、UploadFilePicker CapFile 注入、TriggerNode/默认 Button 与卡片/拖拽区、a11y button+list、Token pictureCardSize≈102/thumbnail48、hit==layout==paint、官方 basic/avatar/defaultFileList/picture-card/picture-circle/fileList/drag/paste）；P1: action/headers/data 真 HTTP、directory 文件夹、iconRender/itemRender/isImageUrl/previewFile 深度、progress ProgressProps 全量、拖拽排序/裁切/OSS 示例、semantic classNames/styles、动画像素级、ConfigProvider 全局、官网逐像素"},
		// Data Display
		{Ant: "Avatar", Status: CovReady, Via: "kit.Avatar / AvatarGroup", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/avatar.md §6（size small|middle|large|number、shape circle|square、icon/IconNode、children 字+gap scale、src+SetPixels/SetImageOK/NotifyImageError+onError fallback、alt/a11y、loading Ticker、disabled、Style 覆盖、响应式 size map+breakpoint、Avatar.Group size/shape 上下文+max.count 溢出 +N 叠压、Token container 24/32/40 + quaternary 底/inverse 字、hit==layout==paint、官方 basic/type/dynamic/badge/group/responsive）；P1: Group max.popover、真 HTTP 解码 src/srcSet/crossOrigin、draggable 桌面拖拽、semantic classNames/styles、ConfigProvider 全局、动画像素级、debug/官网逐像素"},
		{Ant: "Badge", Status: CovReady, Via: "kit.Badge / Ribbon", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/badge.md §6（count/showZero/overflowCount、dot、offset、size medium|small、status+text+processing Ticker、color/Style、title 回落、CountNode、wrapper/独立使用、OnClick/Disabled/a11y、Ribbon placement start|end、Token indicator 20/14 dot/status 6 字号12 paddingInline8、hit==layout==paint、官方 basic/no-wrapper/overflow/dot/change/link/offset/size）；P1: 状态点/多彩/缎带完整 gallery、预设色名全表、ScrollNumber 翻滚/zoom 入场、semantic classNames/styles、ConfigProvider 全局、debug/官网逐像素"},
		{Ant: "Calendar", Status: CovReady, Via: "kit.Calendar", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/calendar.md §6（value/defaultValue/controlled、onChange/onSelect(source)/onPanelChange、mode month|year、fullscreen 全屏/卡片、showWeek ISO 周列、disabledDate/validRange、cellRender/fullCellRender、headerRender、disabled/loading Ticker、a11y role=grid+focus ring、Token fontSize14/radius6|8/year80/month70/miniH256/dateValueH24、hit==layout==paint、官方 basic/notice-calendar/event-range/card/select/lunar/week/customize-header）；P1: semantic classNames/styles、完整 locale、内置农历算法、动画像素级、ConfigProvider 全局、style-class/_semantic、debug/官网逐像素"},
		{Ant: "Card", Status: CovReady, Via: "kit.Card / CardMeta / CardGrid", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/card.md §6（title/extra/cover/actions、loading Skeleton+Ticker、hoverable、size middle|small、type default|inner、variant outlined|borderless、Card.Meta avatar+title+desc、Card.Grid、Token bodyPad24/12 radiusLG8 headerFont16/14 headerH56/30 lineW1、hit==layout==paint、官方 basic/border-less/simple/flexible-content/in-column/loading/grid-card/inner）；P1: tabList/activeTabKey/tabBarExtraContent、boxShadowCard 像素级悬停阴影、semantic classNames/styles、ConfigProvider 全局、动画像素级、debug/官网逐像素"},
		{Ant: "Carousel", Status: CovReady, Via: "kit.Carousel", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/carousel.md §6（arrows、autoplay+autoplaySpeed、dotDuration 进度、adaptiveHeight、dotPlacement top|bottom|start|end、dots、draggable、fade/effect、infinite 默认 true、GoTo/Next/Prev、afterChange/beforeChange、Disabled、键盘方向、Ticker autoplay、Token dot 16×3 gap4 offset12 active24 arrow16/8 stageH160、hit==layout==paint、官方 basic/placement/autoplay/fade/arrows/dot-duration）；P1: scrollx/fade 像素级过渡与 speed/easing/waitForAnimate、自定义 prev/nextArrow、react-slick 其余 Settings、semantic classNames/styles、ConfigProvider 全局、debug/官网逐像素"},
		{Ant: "Collapse", Status: CovReady, Via: "kit.Collapse / CollapseItem", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/collapse.md §6（items/key/label/children、activeKey/defaultActiveKey 受控非受控、onChange、accordion、size small|medium|large、bordered/ghost、collapsible header|icon|disabled、showArrow/expandIcon/expandIconPlacement、extra 不切换、destroyOnHidden/forceRender、嵌套 Collapse、Token headerPad 12×16/content 16/radiusLG=8/headerBg fillSecondary、a11y button+focus ring、Root 稳定、hit==layout==paint、官方 basic/size/accordion/mix/borderless/custom/noarrow/extra）；P1: semantic classNames/styles、展开高度动画像素级、ghost/collapsible 完整 gallery 页、style-class/_semantic、ConfigProvider 全局、官网逐像素"},
		{Ant: "Descriptions", Status: CovReady, Via: "kit.Descriptions", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/descriptions.md §6（items/label/children/span/filled/SpanMap、title/extra、size large|medium|small、bordered、column/ColumnMap+ViewportWidth、layout horizontal|vertical、colon、useRow 行算法、浅 LabelStyle/ContentStyle/Style、Token pad 16/12/8 radiusLG8、a11y group、hit==layout==paint、官方 basic/border/size/responsive/vertical/vertical-border/style-class/block）；P1: semantic classNames/styles 函数形态深度、ConfigProvider 全局、debug/官网逐像素"},
		{Ant: "Empty", Status: CovReady, Via: "kit.Empty", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/empty.md §6（description 默认 No data / 自定义 / HideDescription、image DEFAULT|SIMPLE|Node|src、children footer、浅 Style/ImageStyle/DescriptionStyle/FooterStyle + ClassNames、styles.image.height、内置插画 Canvas 近似 Token 色、Token emptyImgHeight 100/40/35 marginInline8 footerMT16、a11y 装饰图/string img、hit==layout==paint、官方 basic/simple/customize/description/style-class）；P1: ConfigProvider.renderEmpty/全局 empty.image、semantic classNames/styles 函数形态深度、_semantic.tsx debug、真 HTTP/SVG 解码、动画像素级、官网逐像素"},
		{Ant: "Image", Status: CovReady, Via: "kit.Image / ImagePreviewGroup", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/image.md §6（src/alt/width/height、fallback+onError、placeholder+percent+Ticker 不确定进度、preview bool|open|src|scaleStep、OpenPreview/ClosePreview/OnOpenChange、ZoomIn/Out/Rotate/Flip/Reset、ActionsRender 自定义工具栏、ImagePreviewGroup items/current/onChange/onOpenChange、host SetPixels/SetImageOK/NotifyImageError、Token font14 radius6 line1 focus1.5、a11y img+dialog+Esc、hit==layout==paint、官方 basic/placeholder/fallback/preview-group/album/previewSrc/controlled/toolbarRender）；P1: imageRender、mask/cover 高级、nested、真 HTTP 解码 src、movable/滚轮像素级、semantic classNames/styles 深度、ConfigProvider 全局、动画像素级、官网逐像素"},
		{Ant: "List", Status: CovReady, Via: "kit.List", Since: "M4"},
		{Ant: "Popover", Status: CovReady, Via: "kit.Popover", Since: "M2", Notes: "P0 对齐 docs/antd/popover.md §6（title/content Node|string、trigger hover|click|focus|contextMenu、placement 12 向默认 top、arrow+pointAtCenter 默认 true、open/defaultOpen/onOpenChange 受控、autoAdjustOverflow、disabled、zIndex、Esc/外点、浮层内可点、Token innerPadding12/radiusLG8/titleMinWidth177、hit==layout==paint、官方 basic/triggerType/placement/arrow/shift/control/hover-with-click）；P1: semantic classNames/styles style-class、mouseEnter/LeaveDelay 精确秒、color 预设、destroyOnHidden/fresh/getPopupContainer/align、zoom-big 动画像素、ConfigProvider 全局、debug/官网逐像素"},
		{Ant: "QRCode", Status: CovReady, Via: "kit.QRCode", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/qr-code.md §6（value 纯 Go 编码矩阵、size 默认160、color/bgColor Token、bordered+paddingSM8/radiusLG8/lineW1、errorLevel L|M|Q|H、marginSize、icon+iconSize 中心 excavate、status active|expired|loading|scanned、onRefresh、statusRender、type canvas|svg 标签、loading Ticker、a11y img+Refresh、hit==layout==paint、官方 base/icon/status/customStatusRender/type/customSize/customColor/errorlevel/Popover borderless）；P1: 下载 toDataURL/SVG 导出、boostLevel 精确、value string[]、真 HTTP 解码 icon、semantic classNames/styles 函数形态深度、ConfigProvider 全局、type 导出差异、动画像素级、官网逐像素"},
		{Ant: "Segmented", Status: CovReady, Via: "kit.Segmented", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/segmented.md §6（value/defaultValue/onChange 受控非受控、options string|SegmentedOption、disabled 整体/项、size 24/32/40、block 均分、orientation/vertical、shape default|round、icon/icon-only、LabelNode 自定义、动态 SetOptions、a11y radiogroup/radio+方向键、Token trackPad2/itemPad11、hit==layout==paint、官方 basic/vertical/block/shape/disabled/controlled/custom/dynamic）；P1: name 组名、option.tooltip 完整 TooltipProps、三种大小/设置图标/只设置图标/配合 name gallery 页、semantic classNames/styles、thumb 滑动动画像素级、ConfigProvider 全局、debug/官网逐像素"},
		{Ant: "Statistic", Status: CovReady, Via: "kit.Statistic / NewStatisticTimer", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/statistic.md §6（value string|number 默认0、title/prefix/suffix Node|string、precision/decimalSeparator/groupSeparator、formatter、loading Skeleton+Ticker、styles.content+valueStyle 兼容+浅 semantic classNames、Statistic.Timer countdown|countup format/onChange/onFinish Ticker、Token title14/content24/gap4、a11y group、hit==layout==paint、官方 basic/unit/animated/card/timer/style-class）；P1: CountUp 动画像素级、semantic styles 函数形态深度、_semantic.tsx、ConfigProvider 全局、弃用 Countdown 独立类型、官网逐像素"},
		{Ant: "Table", Status: CovReady, Via: "kit.Table / NewTableWith", Since: "M4", Notes: "P0 对齐 docs/antd/table.md §6（columns/dataSource/rowKey、pagination、loading Spin+Ticker、size large|middle|small、bordered/showHeader、title/footer、rowSelection checkbox|radio+selections ALL/INVERT/NONE/自定义、onChange paginate|sort|filter、列 sorter/sortDirections/defaultSortOrder、filters/onFilter/filterMode tree/filterSearch、expandable、scroll.y 固定表头、scroll.x+column.fixed、Empty、rowHoverable、a11y table、Token cellPad 16/12×8/8、官方 basic/jsx/row-selection/operation/custom/head/filter-in-tree/filter-search）；P1: multiple-sorter、可控筛选排序、filterDropdown 自定义、ajax 远程、sticky 复杂、虚拟滚动像素级、nested/edit/drag、semantic classNames/styles、ConfigProvider 全局、官网逐像素"},
		{Ant: "Tag", Status: CovReady, Via: "kit.Tag / CheckableTag / CheckableTagGroup", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/tag.md §6（label/value、color 预设|status|#hex、variant filled|solid|outlined、closable/onClose+PreventDefault、icon/IconSpin、disabled、bordered 兼容、CheckableTag checked/defaultChecked/onChange、CheckableTagGroup options/value/defaultValue/multiple/onChange、Token fontSM12/radiusSM4/padH7/高≈22、a11y close+checkbox、hit==layout==paint、官方 basic/colorful/control/checkable/animation瞬时/icon/status/draggable组合）；P1: semantic classNames/styles、href/target 真链、motion 入场退场像素、完整 dnd-kit、ConfigProvider 全局、debug customize/component-token、官网逐像素"},
		{Ant: "Timeline", Status: CovReady, Via: "kit.Timeline", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/timeline.md §6（items content/title/color/icon/loading/placement、mode start|alternate|end、orientation vertical|horizontal、variant outlined|filled、reverse、item.loading Ticker spinner 替代根 pending、Token dot10/tail2/padBottom20/font14、a11y list/listitem、hit==layout==paint、官方 basic/variant/pending/alternate/horizontal/custom/end/title）；P1: titleSpan 精细占比/百分比字符串、根级 deprecated pending/pendingDot/label/dot/children/position、semantic classNames/styles 深度、动画像素级、ConfigProvider 全局、title-span/semantic/style-class 示例、debug/官网逐像素"},
		{Ant: "Tooltip", Status: CovReady, Via: "kit.Tooltip", Since: "M2", Notes: "P0 对齐 docs/antd/tooltip.md §6（title/TitleNode 空不显示、trigger hover|click|focus、placement 12 向默认 top、arrow+pointAtCenter 默认 true、open/defaultOpen/onOpenChange 受控、color 预设|#hex、mouseEnter/LeaveDelay 默认 0.1 Ticker、autoAdjustOverflow、disabled、zIndex、Token pad6×8/radius6/font14/maxWidth250/spotlight 底+inverse 字、a11y role=tooltip、hit==layout==paint、官方 basic/smooth-transition(无 unique)/placement/arrow/shift/colorful/disabled/wrap-custom）；P1: ConfigProvider tooltip.unique、semantic classNames/styles、zoom-big-fast 动画像素、getPopupContainer/align/fresh/destroyOnHidden、debug/官网逐像素"},
		{Ant: "Tour", Status: CovReady, Via: "kit.Tour", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/tour.md §6（open/current 受控非受控、onChange/onClose/onFinish、steps title/description/cover/target/placement/type/mask/next·prevButtonProps、type default|primary、placement center+12 向默认 bottom、mask bool|color、gap offset/[x,y]+radius、arrow、keyboard Esc、closeIcon、indicatorsRender、actionsRender、disabledInteraction、浅 styles mask/section、Token pad16/radiusLG8/indicator6/gap6·2、a11y dialog+Esc、Portal 稳定、hit==layout==paint、官方 basic/non-modal/placement/mask/indicator/actions-render/gap/style-class）；P1: semantic classNames/styles 函数形态深度、箭头 pointAtCenter 像素级、scrollIntoViewOptions 真滚动、getPopupContainer、动画像素级、ConfigProvider 全局、debug render-panel、官网逐像素"},
		{Ant: "Tree", Status: CovReady, Via: "kit.Tree", Since: "M4"},
		// Feedback
		{Ant: "Alert", Status: CovReady, Via: "kit.Alert", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/alert.md §6（type success|info|warning|error、variant outlined|filled、title/TitleNode、description、showIcon/icon、banner 默认 warning+icon、closable/onClose+PreventDefault/afterClose 瞬时隐藏、action 槽、Token pad8×12/desc16×24/radiusLG8/font14|16、a11y role=alert+close、hit==layout==paint、官方 basic/style/filled/closable/description/icon/banner/loop-banner）；P1: semantic classNames/styles、smooth-closed leave 动画像素、ErrorBoundary、ConfigProvider 全局 closeIcon/*Icon、自定义标题对齐/style-class、完整 action.tsx 多按钮矩阵、debug/官网逐像素"},
		{Ant: "Drawer", Status: CovReady, Via: "kit.Drawer", Since: "M3", Notes: "P0 对齐 docs/antd/drawer.md §6（open/title、placement top|right|bottom|left、size default378|large736|SetSizePx、closable、mask/maskClosable、keyboard Esc、destroyOnHidden、extra/footer、loading Skeleton+Ticker、resizable+resize callbacks/bounds、Token padding24/title16/bgContainer/mask、a11y dialog+focus trap、hit==layout==paint、官方 basic/placement/resizable/loading/extra/form-in-drawer/user-profile）；P1: semantic classNames/styles 深度、动画滑入像素级、getContainer=false/render-in-current DOM 容器裁剪、多层 push、size 字符串/百分比/vw、mask blur、关闭按钮 placement、自定义 drawerRender、ConfigProvider 全局、debug/官网逐像素"},
		{Ant: "Message", Status: CovReady, Via: "kit.Message / NewMessageHost alias", Since: "M3", Notes: "P0 对齐 docs/antd/message.md §6（Open config、Info/Success/Error/Warning/Loading、duration含0常驻、key更新、Destroy、maxCount、stack threshold、top、onClick/onClose、thenable、类型图标、loading Ticker、Token 几何/a11y status、gallery 官方 hooks/other/duration/stack/loading/thenable/style-class/update）；P1: semantic classNames/styles 深度、pauseOnHover 精确计时、入退场动画像素级、浏览器 getContainer/prefixCls/RTL 静态全局上下文、_semantic/debug/官网逐像素"},
		{Ant: "Modal", Status: CovReady, Via: "kit.Modal / ModalHost", Since: "M3", Notes: "P0 对齐 docs/antd/modal.md §6（open 受控、title/content、footer 默认|null|自定义|render(OkBtn,CancelBtn)、okText/cancelText/okType、onOk 不自动关、onCancel/Esc/mask/关闭图标关、confirmLoading、loading 骨架+Ticker、closable、mask/maskClosable、keyboard、centered 默认 false top=100、width=520、destroyOnHidden、ModalHost.Confirm/Info/Success/Error/Warning≡hooks、i18n 文案、Token pad16/24 radiusLG8、a11y dialog+焦点陷阱+Esc、Portal 稳定 multi-id、hit==layout==paint、官方 basic/async/footer/mask/loading/footer-render/hooks/locale）；P1: semantic classNames/styles 函数、modalRender/mousePosition、getContainer/forceRender/scrollLock、ok/cancelButtonProps 全量、mask.blur 真模糊、ConfigProvider locale、动画像素级、嵌套/静态 info 细皮、debug 与官网逐像素"},
		{Ant: "Notification", Status: CovReady, Via: "kit.Notification", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/notification.md §6（Open/Info/Success/Error/Warning、title/description、placement 六向默认 topRight、duration 默认4.5含0常驻、key 更新、closable/手动 Destroy+onClose、onClick、icon/类型图标、actions 按钮组、stack threshold、maxCount/top/bottom、Token width384 pad16×24 radiusLG8 font14|16、a11y role=alert+关闭可聚焦不抢焦、Ticker 自动关、hit==layout==paint、官方 hooks/duration/with-icon/with-btn/custom-icon/placement/update/stack）；P1: showProgress/进度条色、pauseOnHover 精确计时、静态方法全局单例、semantic classNames/styles 深度、stack 阴影像素、getContainer/prefixCls/RTL、动画像素级、ConfigProvider 全局、debug/官网逐像素"},
		{Ant: "Popconfirm", Status: CovReady, Via: "kit.Popconfirm", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/popconfirm.md §6（title/description、icon 默认 warning、okText/cancelText/okType/showCancel、disabled、open/defaultOpen/onOpenChange 受控非受控、onConfirm/onCancel、ConfirmLoading+OnConfirmAsync 异步、trigger 默认 click、placement 12 向默认 top、arrow/autoAdjustOverflow、条件触发拦截、Token 消息底边距8/按钮 small24/面板 pad12、a11y dialog+Esc、hit==layout==paint、官方 basic/locale/placement/shift/dynamic-trigger/icon/async/promise）；P1: semantic classNames/styles、ok/cancelButtonProps 全量、onPopupClick 精细、destroyOnHidden/fresh/延时 trigger、ConfigProvider locale 全局、动画像素级、getPopupContainer、style-class/_semantic/debug、官网逐像素"},
		{Ant: "Progress", Status: CovReady, Via: "kit.Progress", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/progress.md §6（type line|circle|dashboard、size small|medium|SizePx、status normal|exception|active|success 空=自动、percent/SetPercent 不整树 rebuild、showInfo/format、strokeWidth/railColor/strokeColor、dashboard gapDegree/gapPlacement、line 高 8/6、circle 120/60、info gap 8、Token 色、a11y role=progressbar、active Ticker 扫光、hit==layout==paint 非 RepaintBoundary、官方 line/circle/line-mini/circle-micro/circle-mini/dynamic/format/dashboard）；P1: steps 线/圈、strokeLinecap butt|square、渐变 strokeColor、percentPosition、success.percent 双色、semantic classNames/styles、动画像素级 active keyframes、ConfigProvider 全局、分段/边缘/渐变/步骤示例、官网逐像素"},
		{Ant: "Result", Status: CovReady, Via: "kit.Result", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/result.md §6（status info|success|warning|error|403|404|500、title/subTitle、默认/自定义 icon、exception image 250×295、extra 操作区、body 内容区、SetLoading Ticker、自定义 Theme/Style、a11y role=status+label、Token rootPad48/32 icon72 title24 sub14 extra24/gap8 body24×40、hit==layout==paint、官方 success/info/warning/403/404/500/error/customIcon）；P1: semantic classNames/styles 深度、style-class/_semantic 示例、ConfigProvider 全局默认、动画像素级、浏览器-only API、debug 示例与官网逐像素哈希"},
		{Ant: "Skeleton", Status: CovReady, Via: "kit.Skeleton / SkeletonAvatar / Button / Input / Image / Node", Since: "M5", Notes: "P0 对齐 docs/antd/skeleton.md §6（loading 默认 true 切 children、active Ticker 扫光+reduced-motion、avatar/title/paragraph/round、SetParagraphRows 默认 3|2、子组件 Button/Avatar/Input/Image/Node size·shape·block、浅 classNames/styles root/header/section/avatar/title/paragraph、Token titleH16 paragraphH16 blockRadius4 avatar40/32/24 button 2h×h input 5h×h image96、百分比标题 38%/50% 末行段落 61%、hit==layout==paint、官方 basic/complex/active/element/children/list/style-class/_semantic）；P1: title/paragraph/avatar 完整对象形态、styles(info)=> 深度函数、动画像素级 shimmer、复杂自定义节点装饰、浏览器-only API、debug/官网逐像素"},
		{Ant: "Spin", Status: CovReady, Via: "kit.Spin", Since: "M5", Notes: "P0 对齐 docs/antd/spin.md §6（spinning+delay 显示态、size small/medium/large DotSize14/20/32、percent 数值|auto、description+tip 别名、indicator+SetDefaultIndicator、nested children+mask 挡点、浅层 classNames/styles、4-dot/进度环 Canvas+Ticker、ReduceMotion、a11y status/busy、hit==layout==paint、官方 basic/size/nested/tip/delay/custom-indicator/percent/style-class）；P1: fullscreen 视口遮罩、semantic classNames/styles 函数式深度、4-dot keyframes 像素级、ConfigProvider 全局 spin、debug/_semantic、官网逐像素"},
		{Ant: "Watermark", Status: CovReady, Via: "kit.Watermark", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/watermark.md §6（content/多行/WatermarkText 行级 font、image+SetImagePixels/失败回落 content、width/height/rotate=-22/gap=100/offset=gap/2/fontSize=16/colorFill 系、zIndex、inherit+Wrap 传导 Modal/Drawer、onRemove/NotifyRemoved、children 可点 HitTransparent、Loading Ticker、a11y presentation、Token 度量、官方 basic/multi-line/image/custom/portal）；P1: MutationObserver 防删 DOM、真 HTTP 解码 image、alternate clip 与官网 canvas 逐像素、semantic classNames/styles、ConfigProvider 全局、debug/官网哈希"},
		// Other
		{Ant: "Affix", Status: CovReady, Via: "kit.Affix", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/affix.md §6（offsetTop 默认0、offsetBottom、onChange、SetScrollTarget 映射 target、Evaluate/UpdatePosition getFixedTop|Bottom、占位盒不跳变、官方 basic/on-change/target、Token fontSize14/radius6/lineWidth1、a11y presentation、hit≈paint stickDY）；P1: semantic classNames/styles、ConfigProvider 全局、真 position:fixed 出流/Portal 钉、debug/官网逐像素"},
		// Overflow
		{Ant: "Scroll (overflow)", Status: CovReady, Via: "kit.Scroll / ScrollViewport", Since: "Base-ALL"},
		{Ant: "App", Status: CovReady, Via: "Theme+PortalHost", Since: "M1"},
		{Ant: "ConfigProvider", Status: CovReady, Via: "kit.ConfigProvider", Since: "Base-ALL"},
	}
}

// CoverageSummary counts statuses.
func CoverageSummary(entries []CoverageEntry) map[CoverageStatus]int {
	m := map[CoverageStatus]int{}
	for _, e := range entries {
		m[e.Status]++
	}
	return m
}
