package kit

// CoverageStatus for Ant-facing kit capability.
type CoverageStatus string

const (
	// CovReady — kit API exists and is Headless-tested.
	CovReady CoverageStatus = "ready"
	// CovPartial — base available; advanced props deferred.
	CovPartial CoverageStatus = "partial"
	// CovPrimitive — build via primitive only (no kit wrapper yet).
	CovPrimitive CoverageStatus = "primitive"
	// CovLater — planned M4+ / post-M6.
	CovLater CoverageStatus = "later"
)

// CoverageEntry maps one Ant Design component to framework support.
type CoverageEntry struct {
	Ant    string
	Status CoverageStatus
	// Via is kit type or primitive composition hint.
	Via string
	// Milestone when first landed.
	Since string
	Notes string
}

// AntCoverage is the §5.7对照 table (living; update as kit grows).
// Counts are intentional snapshots for M6 DoD.
func AntCoverage() []CoverageEntry {
	return []CoverageEntry{
		// General
		{Ant: "Button", Status: CovReady, Via: "kit.Button", Since: "M1", Notes: "P0 对齐 docs/antd/button.md §6（type/size/shape/variant/color/danger/ghost/block/loading/iconPlacement/a11y）；P1: preset 全色板、loading.delay、autoInsertSpace、wave、href/htmlType"},
		{Ant: "FloatButton", Status: CovReady, Via: "kit.FloatButton / FloatButtonGroup", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/float-button.md §6（type default|primary、shape circle|square、icon/content、tooltip、disabled、loading Ticker、onClick、Group trigger click|hover、open/onOpenChange 受控、placement 四向、closeIcon、a11y AriaLabel、Token 40×40 / square r=8）；P1: badge、BackTop、draggable、href/target/htmlType、semantic classNames/styles、ConfigProvider 全局、展开入场动画像素级、官网逐像素"},
		{Ant: "Icon", Status: CovReady, Via: "kit.Icon / primitive.Icon", Since: "M1", Notes: "P0 对齐 docs/antd/icon.md §6（name 注册表、size 默认16、color Token、rotate、spin Ticker+ReduceMotion、twoTone 实例/全局、SetPainter、CreateFromIconfont+RegisterSource 离线多源、装饰默认 a11y/AriaLabel、hit==layout==paint）；P1: 远程 iconfont.cn scriptUrl、extraCommonProps/真 DOM classNames、全量 SVG Path/上千官方字形、spin 动画像素级/官网哈希、ConfigProvider 全局 Icon 默认"},
		{Ant: "Typography", Status: CovReady, Via: "kit.Typography / NewText / NewTitle / NewParagraph / NewLink", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/typography.md §6（Text/Title/Paragraph/Link、level 1..5 字号 38/30/24/20/16、type secondary|success|warning|danger、disabled、copyable+onCopy+icon、editable Enter/Esc+onChange/onStart/onEnd/onCancel、ellipsis rows/expandable/collapsible/受控 expanded/middle/suffix、actions.placement、strong/code/mark/delete/underline/italic/keyboard、onClick、a11y Label、正文 14 Token、复制成功 Ticker）；P1: semantic classNames/styles、copyable.format/tooltips/tabIndex 深度、editable.autoSize/maxLength/enterIcon/triggerType 全矩阵、ellipsis.tooltip 像素级、复制成功动画像素级、ConfigProvider 全局、后缀/表格示例、官网逐像素"},
		// Layout
		{Ant: "Divider", Status: CovReady, Via: "kit.Divider", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/divider.md §6（orientation/vertical、size small|medium|large|unset margin 8/16/24、variant solid|dashed|dotted + dashed 糖、Title/plain/titlePlacement start|end|center、orientationMargin 默认 0.05、role=separator、Token colorSplit + lineWidth、hit==layout==paint）；P1: semantic classNames/styles 深度、orientationMargin 绝对 px / styles.content.margin 全矩阵、垂直 -0.06em 光学、dashed/dotted 官网纹样逐像素、ConfigProvider 全局"},
		{Ant: "Flex", Status: CovReady, Via: "kit.Flex", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/flex.md §6（orientation/vertical、gap small|medium|large|px 8/16/24、justify、align 默认水平 start/垂直 stretch、wrap、官方 basic/align/gap/wrap/combination、Token、AriaLabel、hit==layout==paint）；P1: flex CSS 简写、component、wrap-reverse、semantic classNames/styles、ConfigProvider 全局 flex 默认、官网逐像素"},
		{Ant: "Grid", Status: CovReady, Via: "kit.Row / kit.Col / NewGrid", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/grid.md §6（Row align/justify/wrap/gutter[h|hv]、Col span/offset/order/push/pull/flex、断点 span xs…xxxl + SetViewportWidth、官方 basic/gutter/offset/sort/flex/flex-align/flex-order/flex-stretch、gridColumns=24、AriaLabel、hit==layout==paint）；P1: gutter/align/justify 响应式 object 与 CSS 字符串 gutter、Col 响应式 object 全字段、useBreakpoint/playground、官方响应式三示例、semantic classNames/styles、ConfigProvider 全局、官网逐像素"},
		{Ant: "Layout", Status: CovReady, Via: "kit.Layout / Header / Sider / Content / Footer", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/layout.md §6（嵌套 Header/Sider/Content/Footer、hasSider 自动/强制、Header 高64、Sider width200/collapsed80/collapsible/collapsed/defaultCollapsed/theme dark|light/trigger 默认|自定义|隐藏/breakpoint+ViewportWidth/onCollapse/onBreakpoint/reverseArrow/overlay collapsedWidth=0、官方 basic/top/top-side/top-side-2/side/custom-trigger/collapsible-overlay/responsive、Token bodyBg/headerBg/siderBg、AriaLabel、hit==layout==paint）；P1: 固定头/固定侧栏、折叠宽度过渡动画像素级、semantic classNames/styles、ConfigProvider 全局、官网逐像素"},
		{Ant: "Space", Status: CovReady, Via: "kit.Space / SpaceCompact / SpaceAddon", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/space.md §6（size small|middle|large|px|[col,row] 默认 small=8、orientation/vertical、align auto→水平center、wrap 仅水平、separator 工厂、官方 base/vertical/size/align/wrap/separator/compact/compact-buttons、Space.Compact block+叠边 gap≈-lineWidth+Button 中间圆角清零、Space.Addon、Token 8/16/24、AriaLabel、hit==layout==paint）；P1: semantic classNames/styles、垂直方向紧凑布局、ConfigProvider 全局、size 双 gap 真 rowGap、逐角 radius、Addon 全语义、官网逐像素"},
		{Ant: "Splitter", Status: CovReady, Via: "kit.Splitter / SplitterPanel", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/splitter.md §6（orientation/vertical、Panel size/defaultSize/min/max px|%、resizable、collapsible+showCollapsibleIcon、lazy 预览、onResize/Start/End/onCollapse、多面板/嵌套 group、键盘条微调、Token splitBarSize=2/trigger=6/spinner=20、AriaLabel、hit==layout==paint）；P1: semantic classNames/styles、collapsible.motion 动画像素级、draggerIcon/自定义折叠图标、onDraggerDoubleClick 双击重置、destroyOnHidden 深度、ConfigProvider 全局、官网逐像素"},
		// Navigation
		{Ant: "Anchor", Status: CovReady, Via: "kit.Anchor", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/anchor.md §6（items/title/href/children、direction vertical|horizontal、affix 默认 true、showInkInFixed、bounds=5、offsetTop/targetOffset、getCurrentAnchor、onChange/onClick、replace History 映射、ink 指示条、ScrollTarget+SectionOffsets+SyncFromScroll 桌面滚动宿主、嵌套二级、a11y navigation+focus ring、Token linkPadding 4/16 inkW=2 fontSize=14）；P1: per-link targetOffset、semantic classNames/styles、ink 滑动动画、真 window history、ConfigProvider 全局、debug/官网逐像素"},
		{Ant: "Breadcrumb", Status: CovReady, Via: "kit.Breadcrumb", Since: "Base-ALL"},
		{Ant: "Dropdown", Status: CovReady, Via: "kit.Dropdown", Since: "M4", Notes: "P0 对齐 docs/antd/dropdown.md §6（trigger hover|click|contextMenu、placement 12 向、arrow/pointAtCenter、open/onOpenChange 受控、disabled、menu items danger/extra/icon/divider/一级 Children、外点/Esc、Token 面板 radiusLG=8 item pad 12×5、a11y menu/menuitem、hit==layout==paint、官方 basic/extra/placement/arrow/item/arrow-center/trigger/event）；P1: Dropdown.Button、popupRender/扩展菜单、多级菜单 gallery、菜单隐藏方式 overlay-open、右键完整 demo、loading、selectable、划词、semantic classNames/styles、destroyOnHidden 深度、ConfigProvider 全局、动画像素级、官网逐像素"},
		{Ant: "Menu", Status: CovReady, Via: "kit.Menu", Since: "M3", Notes: "P0 对齐 docs/antd/menu.md §6（mode vertical|horizontal|inline、items/children/group/divider、selectedKeys/defaultSelectedKeys 受控非受控、openKeys/defaultOpenKeys+onOpenChange、onClick/onSelect/onDeselect、multiple、selectable、disabled/danger/icon/title、theme light|dark + SubMenu ColorTheme、inlineCollapsed 宽80、inlineIndent=24、itemHeight=controlHeightLG=40、collapsed tooltip、键盘 Enter/方向、a11y menu/menuitem、Token 色板、hit==layout==paint、官方 horizontal/inline/inline-collapsed/tooltip/sider-current/vertical/theme/submenu-theme）；P1: semantic classNames/styles、动画像素级、overflowedIndicator 水平省略、forceSubMenuRender、popupRender、triggerSubMenuAction 延时、ConfigProvider 全局、switch-mode/style-class/custom-popup 示例、多级 popup 浮层深度、官网逐像素"},
		{Ant: "Pagination", Status: CovReady, Via: "kit.Pagination", Since: "M4", Notes: "P0 对齐 docs/antd/pagination.md §6（total 条目数/current/pageSize 受控非受控、onChange(page,pageSize)、disabled、size 24/32/40、align、simple+readOnly、showQuickJumper Enter 跳页、showSizeChanger+onShowSizeChange、showTotal、hideOnSinglePage、showLessItems、pageSizeOptions、totalBoundary 自动 sizeChanger、ellipsis jump±5、a11y navigation+focus ring、Token itemH、hit==layout==paint、官方 basic/align/more/changer/jump/mini/simple/controlled）；P1: itemRender 自定义、semantic classNames/styles、responsive 断点、showTitle tooltip、SelectProps 深度 sizeChanger、goButton、总数/全部展示/itemRender/style-class gallery、动画像素级、ConfigProvider 全局、官网逐像素"},
		{Ant: "Steps", Status: CovReady, Via: "kit.Steps", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/steps.md §6（items/title/content/subTitle/icon/disabled/单步 status、current/initial/status、onChange、orientation、size medium|small、type default|panel、variant filled|outlined、titlePlacement、percent 进度环、maxCount 折叠省略、a11y navigation+focus ring、Token icon 32/24、hit==layout==paint、loading icon Ticker、官方 simple/error/vertical/clickable/panel/icon/title-placement/max-count）；P1: type=dot|navigation|inline、responsive 断点、iconRender/progressDot 钩子、semantic classNames/styles、动画像素级、ConfigProvider 全局、progress-dot/nav/inline gallery、官网逐像素"},
		{Ant: "Tabs", Status: CovReady, Via: "kit.Tabs", Since: "M3", Notes: "P0 对齐 docs/antd/tabs.md §6（items/TabItem label+children+icon+disabled、activeKey/defaultActiveKey 受控非受控、onChange/onTabClick、type line|card|editable-card+onEdit remove/add+hideAdd、size small|middle|large、centered、indicator size/align、tabBarExtraContent、tabPlacement top|bottom|left|right、destroyOnHidden、键盘方向、line ink+Ticker 滑动、Token gutter32/cardHeight40、a11y tablist/tab+focus ring、hit==layout==paint、官方 basic/disabled/centered/icon/indicator/slide/extra/size）；P1: more 折叠菜单、renderTabBar/可拖拽、semantic classNames/styles、ink/tabPane 动画像素级、placement/card/editable 完整 gallery 页、自定义新增触发器、ConfigProvider 全局、官网逐像素"},
		// Data Entry
		{Ant: "AutoComplete", Status: CovReady, Via: "kit.AutoComplete", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/auto-complete.md §6（value/defaultValue/onChange 受控、onSearch/onSelect、disabled、size 24/32/40、variant outlined|filled|borderless|underlined、status error|warning、open/defaultOpen/onOpenChange、options+一层 group、filterOption bool|func、defaultActiveFirstOption、allowClear/onClear、notFoundContent、children Input|Search|TextArea、popupMatchSelectWidth、loading Ticker、键盘 ↑↓EnterEsc、a11y combobox/listbox、官方 basic/options/custom/non-case-sensitive/certain-category/uncertain-category/status/variant）；P1: backfill、virtual 虚拟滚动、popupRender、semantic classNames/styles、自定义清除按钮/style-class 示例、动画像素级、ConfigProvider 全局、官网逐像素"},
		{Ant: "Cascader", Status: CovReady, Via: "kit.Cascader", Since: "M4", Notes: "P0 对齐 docs/antd/cascader.md §6（value/defaultValue/onChange 单选路径、multiple+onChangeMulti、options CascaderOption、disabled、size 24/32/40、variant outlined|filled|borderless|underlined、status error|warning、open/defaultOpen/onOpenChange、placement 四角、allowClear 默认 true、placeholder、changeOnSelect、expandTrigger click|hover、displayRender、showCheckedStrategy SHOW_PARENT|SHOW_CHILD、showSearch 路径过滤、loadData+Loading Ticker、自定义 TriggerNode、a11y combobox/listbox+focus ring、官方 basic/default-value/custom-trigger/hover/disabled-option/change-on-select/multiple/showCheckedStrategy）；P1: showSearch 对象形态 filter/limit/sort/render、tagRender/optionRender/popupRender/fieldNames、maxTagCount=responsive 像素级、虚拟长列、semantic classNames/styles、动画像素级、ConfigProvider 全局、大小/自定义已选项/搜索高级/动态加载完整 demo 视觉、官网逐像素"},
		{Ant: "Checkbox", Status: CovReady, Via: "kit.Checkbox / CheckboxGroup", Since: "M2", Notes: "P0 对齐 docs/antd/checkbox.md §6（checked/defaultChecked/controlled、indeterminate、onChange、disabled、title、Group value/defaultValue/options/name、Add+SetBody 布局、a11y role=checkbox、Token 指示器16×16 r=4、官方 basic/disabled/controller/group/check-all/layout/style-class/_semantic）；P1: semantic classNames/styles 函数形态深度、onFocus/onBlur、Wave/动画像素级、ConfigProvider 全局、debug/官网逐像素"},
		{Ant: "ColorPicker", Status: CovReady, Via: "kit.ColorPicker", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/color-picker.md §6（value/defaultValue/onChange/onChangeComplete、open/onOpenChange、size 24/32/40、mode single|gradient、showText+自定义文本钩子、disabled、disabledAlpha、allowClear/onClear、format hex|rgb|hsb、placement 四角、trigger click|hover、TriggerNode、HSB 面板+滑条、Token 色块/面板宽234、a11y combobox+focus ring、hit==layout==paint、官方 base/size/controlled/line-gradient/text-render/disabled/disabled-alpha/allowClear）；P1: presets 预设色、面板 format 切换 UI/disabledFormat/onFormatChange、panelRender、arrow 像素级、自定义触发器完整 demo/自定义 trigger 事件 demo、semantic classNames/styles、多 stop 渐变编辑器深度、动画像素级、ConfigProvider 全局、debug/官网逐像素"},
		{Ant: "DatePicker", Status: CovReady, Via: "kit.DatePicker / NewRangePicker", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/date-picker.md §6（value/defaultValue/onChange、picker date|week|month|quarter|year、format+FormatMask、showTime、needConfirm、multiple、RangePicker、disabled/disabledDate、size 24/32/40、variant、status、open/onOpenChange、placement 四角、allowClear、官方 basic/range/multiple/needConfirm/switchable/format/time/mask、a11y combobox+focus ring、hit==layout==paint）；P1: 受控 mode 面板、minDate/maxDate/presets/cellRender、输入 mask 逐键编辑深度、semantic classNames/styles、动画像素级、ConfigProvider 全局、禁用/允许留空/日期限定完整 demo、官网逐像素"},
		{Ant: "Form", Status: CovReady, Via: "kit.Form + FormModel", Since: "M3"},
		{Ant: "Input", Status: CovReady, Via: "kit.Input / Search / Password / TextArea", Since: "M2", Notes: "P0 对齐 docs/antd/input.md §6（value/defaultValue/onChange 受控、disabled/readOnly、maxLength、onPressEnter、size 24/32/40、type text|password、variant outlined|filled|borderless|underlined、status error|warning、allowClear、prefix/suffix、Input.Search onSearch+enterButton+loading Ticker、Input.TextArea rows+autoSize min/maxRows、Input.Password visibilityToggle 掩码、a11y textbox+AriaLabel、Token paddingInline≈11/radius6、hit==layout==paint）；P1: showCount/count CountConfig、Input.OTP、formatter 展示、searchIcon/iconRender 深度、semantic classNames/styles、ConfigProvider 全局、debug/官网逐像素"},
		{Ant: "InputNumber", Status: CovReady, Via: "kit.InputNumber", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/input-number.md §6（value/defaultValue/onChange 受控、min/max/step/precision、controls/keyboard/changeOnWheel/changeOnBlur、disabled/readOnly、size 24/32/40、variant outlined|filled|borderless|underlined、status error|warning、mode input|spinner API、stringMode、formatter/parser、onStep/onPressEnter、a11y spinbutton、Token controlWidth90/handleWidth、官方 basic/size/disabled/digit/formatter/keyboard/change-on-wheel/variant）；P1: 前缀/后缀、超出边界完整 demo、自定义 up/down 图标、拨轮完整视觉、semantic classNames/styles、动画像素级、ConfigProvider 全局、debug/官网逐像素"},
		{Ant: "Mentions", Status: CovReady, Via: "kit.Mentions", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/mentions.md §6（value/defaultValue/onChange、disabled/readOnly、size 字号档、variant outlined|filled|borderless|underlined、status error|warning、options、prefix 默认@/多触发、split、placement top|bottom、allowClear/onClear、onSearch/onSelect、filterOption、loading Ticker、rows 多行、GetMentions、a11y combobox/listbox+键盘、官方 basic/size/variant/async/form/prefix/readonly/placement）；P1: allowClear 自定义 clearIcon 完整 demo、autoSize、自定义 status 完整页、validateSearch/onPopupScroll、semantic classNames/styles、动画像素级、ConfigProvider 全局、官网逐像素"},
		{Ant: "Radio", Status: CovReady, Via: "kit.Radio / RadioGroup / Radio.Button", Since: "M2", Notes: "P0 对齐 docs/antd/radio.md §6（checked/defaultChecked/controlled、Group value/defaultValue/options/name、onChange、disabled、size 24/32/40 仅 button、optionType default|button、buttonStyle outline|solid、block、orientation/vertical、title、Radio.Button、a11y role=radio/radiogroup+focus ring+方向键、Token 圆点16/Button高32、hit==layout==paint、官方 basic/disabled/radiogroup/radiogroup-more/radiogroup-block/radiogroup-options/radiobutton/radiogroup-with-name）；P1: semantic classNames/styles 函数形态、size.tsx/radiobutton-solid 完整页、_semantic、Wave/动画像素级、ConfigProvider 全局、debug/官网逐像素"},
		{Ant: "Rate", Status: CovReady, Via: "kit.Rate", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/rate.md §6（value/defaultValue/controlled float64、onChange/onHoverChange、disabled、size small|middle|large→starSize 15/20/25、count、allowClear 默认 true、allowHalf 半星命中+clip 绘制、character 字符串/CharacterAt(index)、tooltips string[]、keyboard 方向键、a11y radiogroup/radio+focus ring、Token yellow6 填充/fillSecondary 空底、hit==layout==paint、Root 身份稳定、官方 basic/size/half/text/disabled/clear/character/character-function）；P1: character 复杂节点/图标、tooltips 完整 TooltipProps、hover scale(1.1) 像素级、semantic classNames/styles、ConfigProvider 全局、动画像素级、debug/官网逐像素"},
		{Ant: "Select", Status: CovReady, Via: "kit.Select", Since: "M3", Notes: "P0 对齐 docs/antd/select.md §6（value/defaultValue/onChange 单选、Values/onChangeMulti 多选 tags、disabled、loading Ticker 后缀、size 24/32/40、variant outlined|filled|borderless|underlined、status error|warning、open/defaultOpen/onOpenChange 受控、options、title、placement 四角、allowClear/onClear、showSearch+optionFilterProp/filterOption/filterSort/onSearch、mode single|multiple|tags、maxTagCount +N 折叠、optionRender、notFoundContent、defaultActiveFirstOption、popupMatchSelectWidth、listHeight=256、键盘 ↑↓EnterEsc、a11y combobox/listbox+focus ring、Token 高度/圆角/边框、hit==layout==paint、官方 basic/search/search-filter-option/search-multi-field/multiple/size/option-render/search-sort）；P1: semantic classNames/styles、动画像素级/虚拟列表、optgroup 分组、联动 coordinate、label-in-value 完整、自动分词、前后缀、popupRender 扩展菜单、隐藏已选、variant/status 完整 gallery、maxCount、响应式 maxTagCount、大数据、ConfigProvider 全局、官网逐像素"},
		{Ant: "Slider", Status: CovReady, Via: "kit.Slider", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/slider.md §6（value/defaultValue/controlled、min/max/step/stepNull、onChange/onChangeComplete、range+Values/OnRangeChange、disabled、keyboard、marks/included/dots、orientation/vertical、tooltip open Auto|Always|Never + formatter/formatterNull + placement、a11y role=slider、Token controlSize10/railSize4/handleSize10/handleHover12/dotSize8、官方 basic/input-number/icon-slider/tip-formatter/event/mark/vertical/show-tooltip）；P1: reverse、range.draggableTrack、multiple/editable/maxCount、range 单柄 disabled[]、semantic classNames/styles、handle hover 动画像素级、ConfigProvider 全局、debug/官网逐像素"},
		{Ant: "Switch", Status: CovReady, Via: "kit.Switch", Since: "M2", Notes: "P0 对齐 docs/antd/switch.md §6（checked/value、defaultChecked/defaultValue、controlled、onChange/onClick、disabled、loading、size medium|small、checkedChildren/unCheckedChildren 字符串、a11y role=switch Space/Enter+focus ring、Token 轨 44×22/28×16 + colorPrimary 开态/colorTextQuaternary 关态、thumb FloatAnim+loading Ticker、hit==layout==paint）；P1: semantic classNames/styles、复杂 ReactNode 内文、Wave/像素级 handle 拉伸、官网逐像素"},
		{Ant: "TimePicker", Status: CovReady, Via: "kit.TimePicker / NewTimeRangePicker", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/time-picker.md §6（value/defaultValue/onChange TimeValue、disabled、size 24/32/40、variant outlined|filled|borderless|underlined、status error|warning、open/defaultOpen/onOpenChange、placement 四角、allowClear/onClear、format 列显隐、hour/minute/secondStep、needConfirm+OK、showNow、disabledTime、use12Hours L1、Range/NewTimeRangePicker L1、renderExtraFooter、loading Ticker、a11y combobox+focus ring、Token 高度/圆角、hit==layout==paint、官方 basic/value/size/need-confirm/disabled/hide-column/interval-options/addon）；P1: cellRender/hideDisabledOptions/changeOnScroll 像素级、semantic classNames/styles、12h/range/variant/status/suffix 完整 gallery 页、列虚拟滚动、ConfigProvider 全局、官网逐像素"},
		{Ant: "Transfer", Status: CovReady, Via: "kit.Transfer", Since: "M4", Notes: "P0 对齐 docs/antd/transfer.md §6（dataSource/targetKeys 受控、selectedKeys/onSelectChange、onChange(direction,moveKeys)、disabled、status error|warning、oneWay+右栏移除、showSearch+filterOption+onSearch、showSelectAll、actions/titles、render 字符串、footer、pagination pageSize=10 simple、ListBody 表格穿梭、操作钮 loading Ticker、Token listWidth180/listHeight200/listWidthLG250/header40/item32、a11y group/listbox、官方 basic/oneWay/search/advanced/custom-item/actions/large-data/table-transfer）；P1: semantic classNames/styles、selectionsIcon 顶栏下拉、selectAllLabels、树穿梭 tree-transfer、style-class/_semantic、动画像素级/超大虚拟、ConfigProvider 全局、官网逐像素"},
		{Ant: "TreeSelect", Status: CovReady, Via: "kit.TreeSelect", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/tree-select.md §6（value/defaultValue/onChange 单选、Values/onChangeMulti 多选、treeData TreeSelectNode、disabled、size 24/32/40、variant outlined|filled|borderless|underlined、status error|warning、open/defaultOpen/onOpenChange、placement 四角、allowClear/onClear、showSearch+onSearch、multiple、treeCheckable+showCheckedStrategy SHOW_CHILD|PARENT|ALL、treeCheckStrictly、treeDefaultExpandAll、treeLine/treeIcon、treeDataSimpleMode、loadData+Loading Ticker、title、listHeight=256、popupMatchSelectWidth、键盘 ↑↓←→EnterEsc、a11y combobox/option+focus ring、Token 高度/圆角/边框、hit==layout==paint、官方 basic/multiple/treeData/checkable/async/treeLine/placement/variant）；P1: semantic classNames/styles、动画像素级/复杂虚拟列表、maxCount、前后缀 suffix/prefix、自定义状态完整页、自定义语义 class、labelInValue 完整、fieldNames、switcherIcon 自定义、浏览器-only API、ConfigProvider 全局、官网逐像素"},
		{Ant: "Upload", Status: CovReady, Via: "kit.Upload / NewUploadDragger", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/upload.md §6（fileList/defaultFileList/Controlled、onChange、UploadFile.status/percent、disabled、listType text|picture|picture-card|picture-circle、type select|drag、customRequest 桌面主路径+默认 Ticker 模拟、beforeUpload Proceed|SkipUpload|Reject、onRemove/onPreview/onDrop、maxCount 1 替换/>1 截断、accept 扩展名/MIME、multiple、showUploadList、pastable+PasteFiles/PasteProvider、DropFiles、UploadFilePicker CapFile 注入、TriggerNode/默认 Button 与卡片/拖拽区、a11y button+list、Token pictureCardSize≈102/thumbnail48、hit==layout==paint、官方 basic/avatar/defaultFileList/picture-card/picture-circle/fileList/drag/paste）；P1: action/headers/data 真 HTTP、directory 文件夹、iconRender/itemRender/isImageUrl/previewFile 深度、progress ProgressProps 全量、拖拽排序/裁切/OSS 示例、semantic classNames/styles、动画像素级、ConfigProvider 全局、官网逐像素"},
		// Data Display
		{Ant: "Avatar", Status: CovReady, Via: "kit.Avatar / AvatarGroup", Since: "Base-ALL", Notes: "P0 对齐 docs/antd/avatar.md §6（size small|middle|large|number、shape circle|square、icon/IconNode、children 字+gap scale、src+SetPixels/SetImageOK/NotifyImageError+onError fallback、alt/a11y、loading Ticker、disabled、Style 覆盖、响应式 size map+breakpoint、Avatar.Group size/shape 上下文+max.count 溢出 +N 叠压、Token container 24/32/40 + quaternary 底/inverse 字、hit==layout==paint、官方 basic/type/dynamic/badge/group/responsive）；P1: Group max.popover、真 HTTP 解码 src/srcSet/crossOrigin、draggable 桌面拖拽、semantic classNames/styles、ConfigProvider 全局、动画像素级、debug/官网逐像素"},
		{Ant: "Badge", Status: CovReady, Via: "kit.Badge", Since: "Base-ALL"},
		{Ant: "Calendar", Status: CovReady, Via: "kit.Calendar", Since: "Base-ALL"},
		{Ant: "Card", Status: CovReady, Via: "kit.Card", Since: "Base-ALL"},
		{Ant: "Carousel", Status: CovReady, Via: "kit.Carousel", Since: "Base-ALL"},
		{Ant: "Collapse", Status: CovReady, Via: "kit.Collapse", Since: "Base-ALL"},
		{Ant: "Descriptions", Status: CovReady, Via: "kit.Descriptions", Since: "Base-ALL"},
		{Ant: "Empty", Status: CovReady, Via: "kit.Empty", Since: "Base-ALL"},
		{Ant: "Image", Status: CovReady, Via: "kit.Image", Since: "Base-ALL", Notes: "Src+SetPixels sample; GPU texture later"},
		{Ant: "List", Status: CovReady, Via: "kit.List", Since: "M4"},
		{Ant: "Popover", Status: CovReady, Via: "kit.Popover", Since: "M2"},
		{Ant: "QRCode", Status: CovReady, Via: "kit.QRCode", Since: "Base-ALL", Notes: "deterministic modules; codec later"},
		{Ant: "Segmented", Status: CovReady, Via: "kit.Segmented", Since: "Base-ALL"},
		{Ant: "Statistic", Status: CovReady, Via: "kit.Statistic", Since: "Base-ALL"},
		{Ant: "Table", Status: CovReady, Via: "kit.Table", Since: "M4", Notes: "virtual rows; fixed header (Column, not in-scroll sticky)"},
		{Ant: "Tag", Status: CovReady, Via: "kit.Tag", Since: "Base-ALL"},
		{Ant: "Timeline", Status: CovReady, Via: "kit.Timeline", Since: "Base-ALL"},
		{Ant: "Tooltip", Status: CovReady, Via: "kit.Tooltip", Since: "M2"},
		{Ant: "Tour", Status: CovReady, Via: "kit.Tour", Since: "M5"},
		{Ant: "Tree", Status: CovReady, Via: "kit.Tree", Since: "M4"},
		// Feedback
		{Ant: "Alert", Status: CovReady, Via: "kit.Alert", Since: "Base-ALL"},
		{Ant: "Drawer", Status: CovReady, Via: "kit.Drawer", Since: "M3"},
		{Ant: "Message", Status: CovReady, Via: "kit.MessageHost", Since: "M3"},
		{Ant: "Modal", Status: CovReady, Via: "kit.Modal", Since: "M3"},
		{Ant: "Notification", Status: CovReady, Via: "MessageHost queue", Since: "M3"},
		{Ant: "Popconfirm", Status: CovReady, Via: "kit.Popconfirm", Since: "Base-ALL"},
		{Ant: "Progress", Status: CovReady, Via: "kit.Progress / ProgressRing", Since: "M5"},
		{Ant: "Result", Status: CovReady, Via: "kit.Result", Since: "Base-ALL"},
		{Ant: "Skeleton", Status: CovReady, Via: "kit.Skeleton", Since: "M5"},
		{Ant: "Spin", Status: CovReady, Via: "kit.Spin", Since: "M5"},
		{Ant: "Watermark", Status: CovReady, Via: "kit.Watermark", Since: "Base-ALL"},
		// Other
		{Ant: "Affix", Status: CovReady, Via: "kit.Affix / Sticky", Since: "Base-ALL"},
		// Overflow
		{Ant: "Scroll (overflow)", Status: CovReady, Via: "kit.Scroll / ScrollViewport", Since: "Base-ALL"},
		{Ant: "App", Status: CovReady, Via: "Theme+PortalHost", Since: "M1"},
		{Ant: "ConfigProvider", Status: CovReady, Via: "kit.ConfigProvider", Since: "Base-ALL"},
	}
}

// CoverageSummary counts statuses.
func CoverageSummary(entries []CoverageEntry) map[CoverageStatus]int {
	m := map[CoverageStatus]int{}
	for _, e := range entries {
		m[e.Status]++
	}
	return m
}
